/**
 * Localization Provider
 * Manages language switching between English and Arabic with RTL support
 */

import React, { createContext, useContext, useState, useCallback, useMemo, useEffect } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'ar';

interface LocalizationContextType {
  language: Language;
  isRTL: boolean;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = '@elsaif_analysis_language';

// Translation dictionaries
const translations = {
  en: {
    // Splash Screen
    'splash.initializing': 'INITIALIZING',

    // Login Screen
    'login.title': 'Login',
    'login.subtitle': 'Secure access portal for authorized\npersonnel only.',
    'login.email': 'Email Address',
    'login.emailPlaceholder': 'you@Alsaif-analysis.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.forgotPassword': 'Forgot Password?',
    'login.loginButton': 'Log In',
    'login.secureConnection': 'SECURE CONNECTION',
    'login.faceId': 'Face ID',
    'login.touchId': 'Touch ID',
    'login.biometricLogin': 'Biometric Login',
    'login.encryption': 'Protected by 256-bit SSL encryption.\nv4.2.0 (Build 2024.10)',
    'login.noAccount': "Don't have an account? ",
    'login.signUp': 'Sign Up',

    // Register Screen
    'register.title': 'Create Your Account',
    'register.subtitle': 'Unlock smart stock insights and\nreal-time market data.',
    'register.fullName': 'Full Name',
    'register.fullNamePlaceholder': 'e.g. John Doe',
    'register.email': 'Email Address',
    'register.emailPlaceholder': 'name@example.com',
    'register.password': 'Password',
    'register.passwordPlaceholder': 'Enter your password',
    'register.confirmPassword': 'Confirm Password',
    'register.confirmPasswordPlaceholder': 'Re-enter your password',
    'register.nationality': 'Nationality',
    'register.nationalityPlaceholder': 'Enter your nationality',
    'register.passwordStrength': 'Password strength:',
    'register.weak': 'Weak',
    'register.medium': 'Medium',
    'register.strong': 'Strong',
    'register.agreeToTerms': 'I agree to the ',
    'register.termsOfService': 'Terms of Service',
    'register.and': ' and ',
    'register.privacyPolicy': 'Privacy Policy',
    'register.signUpButton': 'Sign Up',
    'register.alreadyHaveAccount': 'Already have an account? ',
    'register.logIn': 'Log in',

    // Forgot Password Screen
    'forgotPassword.title': 'Forgot Password?',
    'forgotPassword.subtitle': "Enter your email address and we'll send you instructions to reset your password",
    'forgotPassword.emailPlaceholder': 'you@example.com',
    'forgotPassword.sendLink': 'Send Reset Link',
    'forgotPassword.successTitle': 'Email Sent!',
    'forgotPassword.successSubtitle': 'Check your email for reset instructions',
    'forgotPassword.successMessage': "We've sent password reset instructions to",
    'forgotPassword.resendText': "Didn't receive the email? Resend",
    'forgotPassword.rememberPassword': 'Remember your password? ',
    'forgotPassword.backToLogin': 'Back to Login',

    // Reset Password Screen
    'resetPassword.title1': 'Reset Password',
    'resetPassword.successTitle1': 'Password Reset!',
    'resetPassword.subtitle': 'Enter the verification code sent to',
    'resetPassword.successSubtitle': 'Your password has been reset successfully',
    'resetPassword.allSet': 'All Set!',
    'resetPassword.allSetSubtitle': 'You can now log in with your new password',
    'resetPassword.verificationCode': 'Verification Code',
    'resetPassword.codePlaceholder': '000000',
    'resetPassword.codeHelper': 'Enter the 6-digit code sent to your email',
    'resetPassword.newPassword': 'New Password',
    'resetPassword.passwordPlaceholder': 'Create a strong password',
    'resetPassword.passwordRequirementsMet': '✓ Password meets all requirements',
    'resetPassword.confirmPassword': 'Confirm Password',
    'resetPassword.confirmPlaceholder': 'Re-enter your password',
    'resetPassword.resetButton': 'Reset Password',

    // Chat List Screen
    'chatList.title': 'Chats',
    'chatList.searchPlaceholder': 'Search advisor or ticker...',
    'chatList.filterAll': 'All',
    'chatList.filterUnread': 'Unread',
    'chatList.filterPremium': 'Premium',
    'chatList.filterGroups': 'Groups',
    'chatList.pinned': 'PINNED',
    'chatList.recent': 'RECENT',
    'chatList.loadingConversations': 'Loading conversations...',
    'chatList.noConversations': 'No Conversations',
    'chatList.noConversationsMessage': 'Start a conversation to connect with advisors and groups.',
    'chatList.noResults': 'No Results',
    'chatList.noResultsMessage': 'Try adjusting your search or filters.',
    'chatList.errorTitle': 'Connection Error',
    'chatList.errorMessage': 'Unable to load conversations. Please check your connection.',
    'chatList.tryAgain': 'Try Again',
    'chatList.newChat': 'New Chat',
    'chatList.noMessages': 'No messages yet',
    'chatList.searchUsers': 'Search users by name or email...',
    'chatList.startTyping': 'Start typing to search users',
    'chatList.noUsersFound': 'No users found',
    'chatList.startingChatWith': 'Starting chat with',
    'chatList.initialMessagePlaceholder': 'Type an initial message (optional)...',
    'chatList.startChat': 'Start Conversation',
    'chatList.createError': 'Failed to create conversation',
    'chatList.manageChat': 'Manage Conversation',
    'chatList.archive': 'Archive',
    'chatList.delete': 'Delete',
    'chatList.block': 'Block',

    // Conversation Screen
    'conversation.typeMessage': 'Type a message...',
    'conversation.send': 'Send',
    'conversation.today': 'Today',
    'conversation.yesterday': 'Yesterday',
    'conversation.edited': 'Edited',
    'conversation.deleted': 'This message was deleted',
    'conversation.noMessages': 'No messages yet',
    'conversation.startConversation': 'Start a conversation',
    'conversation.loading': 'Loading messages...',
    'conversation.retry': 'Retry',
    'conversation.failed': 'Failed to send',
    'conversation.sending': 'Sending...',
    'conversation.sent': 'Sent',
    'conversation.delivered': 'Delivered',
    'conversation.read': 'Read',
    'conversation.online': 'Online',
    'conversation.offline': 'Offline',
    'conversation.typing': 'typing...',
    'conversation.participants': '{count} participants',
    'conversation.reply': 'Reply',
    'conversation.edit': 'Edit',
    'conversation.delete': 'Delete',
    'conversation.forward': 'Forward',
    'conversation.pin': 'Pin',
    'conversation.unpin': 'Unpin',
    'conversation.copy': 'Copy',
    'conversation.pinned': 'Pinned',
    'conversation.forwarded': 'Forwarded from',
    'conversation.editMessage': 'Edit Message',
    'conversation.replyTo': 'Reply to',
    'conversation.editYourMessage': 'Edit your message...',
    'conversation.typeReply': 'Type your reply...',
    'conversation.cannotSendMessages': 'You cannot send messages in this chat',
    'conversation.pinnedMessages': 'Pinned Message',
    'conversation.peopleTyping': 'people are typing...',
    'conversation.groupChat': 'Group Chat',
    'conversation.chat': 'Chat',
    'conversation.editing': 'Editing',
    'conversation.replyingTo': 'Replying to',
    'conversation.deleteMessage': 'Delete Message',
    'conversation.deleteConfirm': 'Are you sure you want to delete this message? This action cannot be undone.',

    // Chat Settings
    'chat.settings.title': 'Chat Settings',
    'chat.settings.adminControls': 'Admin Controls',
    'chat.settings.onlyAdminsCanSend': 'Only admins can send',
    'chat.settings.onlyAdminsCanSendDescription': 'Only admins and allowed members can send messages',
    'chat.settings.yourPermissions': 'Your Permissions',
    'chat.settings.youCanSend': 'You can send messages',
    'chat.settings.youCannotSend': 'You cannot send messages',
    'chat.settings.youAreAdmin': 'You are an admin',
    'chat.settings.youAreMember': 'You are a member',
    'chat.settings.members': 'Members',
    'chat.settings.memberCount': '{count} members',
    'chat.settings.admin': 'Admin',
    'chat.settings.canSend': 'Can send',
    'chat.settings.kickTitle': 'Remove Member',
    'chat.settings.kickConfirm': 'Remove {name} from this group?',
    'chat.settings.kick': 'Remove',
    'chat.settings.updateFailed': 'Failed to update settings',
    'chat.settings.grantFailed': 'Failed to grant permission',
    'chat.settings.revokeFailed': 'Failed to revoke permission',
    'chat.settings.kickFailed': 'Failed to remove member',
    'chat.settings.premiumGroup': 'Premium Members',
    'chat.settings.communityGroup': 'Community Group',

    // Common
    'common.appName': 'Alsaif-Analysis',
    'common.ad': 'Ad',
    'common.tagline': 'Smarter decisions. Higher returns.',
    'common.settings': 'Settings',
    'common.theme': 'Theme',
    'common.language': 'Language',
    'common.dark': 'Dark',
    'common.light': 'Light',
    'common.all': 'All',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.success': 'Success',
    'common.comingSoon': 'Coming Soon',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.author': 'Unknown Author',
    'common.details': 'Details',
    'common.on': 'on',
    'common.loadMore': 'Load More',
    'common.seeAll': 'See All',

    // Time
    'time.justNow': 'Just now',
    'time.minutesAgo': '{count}m ago',
    'time.hoursAgo': '{count}h ago',
    'time.daysAgo': '{count}d ago',
    'time.weeksAgo': '{count}w ago',
    'time.monthsAgo': '{count}mo ago',
    'time.readTime': '{count} min read',

    // Bottom Tab Navigation
    'tabs.home': 'Home',
    'tabs.chat': 'Chat',
    'tabs.market': 'Market',
    'tabs.profile': 'Profile',
    'tabs.admin': 'Admin',

    // Market Screen
    'market.title': 'Market Data',
    'market.dubai': 'Dubai',
    'market.abuDhabi': 'Abu Dhabi',
    'market.selectMarketPrompt': 'Select a market to explore',
    'market.noData': 'No market data available',
    'market.open': 'Open',
    'market.high': 'High',
    'market.low': 'Low',
    'market.prevClose': 'Prev Close',
    'market.volume': 'Volume',
    'market.priceHistory': 'Price History',

    // Profile Screen
    'profile.title': 'Profile',
    'profile.user': 'User',
    'profile.loading': 'Loading profile...',
    'profile.memberSince': 'Member since',
    'profile.preferences': 'Preferences',
    'profile.darkMode': 'Dark Mode',
    'profile.darkModeDesc': 'Toggle dark theme',
    'profile.language': 'Language',
    'profile.subscription': 'Subscription',
    'profile.premium': 'Premium',
    'profile.free': 'Free',
    'profile.premiumPlan': 'Premium Plan',
    'profile.freePlan': 'Free Plan',
    'profile.active': 'Active',
    'profile.renewsOn': 'Renews on',
    'profile.autoRenewal': 'Auto-renewal enabled',
    'profile.manageSubscription': 'Manage Subscription',
    'profile.upgradeToPremium': 'Upgrade to Premium',
    'profile.actions': 'Actions',
    'profile.logout': 'Logout',
    'profile.logoutConfirm': 'Are you sure you want to logout?',
    'profile.premiumDescription': 'Access to all premium insights and tools',
    'profile.freeDescription': 'Limited access to insights',
    'profile.expiresOn': 'Expires on',
    'profile.account': 'Account',
    'profile.security': 'Security',
    'profile.support': 'Support',
    'profile.privacy': 'Privacy, Terms & Conditions',
    'profile.deleteAccount': 'Delete Account',
    'profile.logoutTitle': 'Logout',
    'profile.logoutMessage': 'Are you sure you want to logout?',
    'profile.editProfile': 'Edit Profile',
    'profile.name': 'Name',
    'profile.enterName': 'Enter your name',
    'profile.avatarUrl': 'Avatar URL (optional)',
    'profile.saveChanges': 'Save Changes',
    'profile.error': 'Error',
    'profile.success': 'Success',
    'profile.nameRequired': 'Name cannot be empty',
    'profile.nameMinLength': 'Name must be at least 2 characters',
    'profile.nameMaxLength': 'Name cannot exceed 50 characters',
    'profile.profileUpdated': 'Profile updated successfully',
    'profile.updateFailed': 'Failed to update profile',
    'profile.comingSoon': 'Coming Soon',
    'profile.themeToggleComingSoon': 'Theme toggle will be available soon!',
    'profile.themeChanged': 'Theme Changed',
    'profile.themeChangedMessage': 'Theme has been updated successfully!',
    'profile.languageChanged': 'Language Changed',
    'profile.languageChangedMessage': 'App will restart to apply language changes.',

    // Insights Screen
    'insights.title': 'Insights',
    'insights.freeInsights': 'Free Advice',
    'insights.premiumInsights': 'Premium Insights',
    'insights.noInsights': 'No insights available',
    'insights.noInsightsMessage': 'Check back later for new updates.',
    'insights.loading': 'Loading insights...',
    'insights.details': 'Insight Details',
    'insights.comments': 'Comments',
    'insights.noComments': 'No comments yet',
    'insights.loadMoreComments': 'Load more comments',
    'insights.addComment': 'Add a comment...',
    'insights.loadingInsight': 'Loading insight...',
    'insights.premiumInsight': 'Premium Insight',
    'insights.types.free': 'Free Advice',
    'insights.types.premium': 'Premium Insight',
    'insights.premiumMessage': 'This deep dive analysis is exclusive to Premium subscribers. Unlock full access to our expert market strategies.',
    'insights.unlockNow': 'Unlock Now',
    'insights.share': 'Share',
    'insights.shareComingSoon': 'Share functionality coming soon',
    'insights.comment': 'Comment',
    'insights.commentComingSoon': 'Comment input coming soon',
    'insights.replyingTo': 'Replying to',
    'insights.retry': 'Retry',
    'insights.requestTitle': 'Propose an Insight',
    'insights.requestDetails': 'Insight Details',
    'insights.submitRequest': 'Submit Proposal',
    'insights.requestPlaceholder': 'e.g., Analysis of NVDA earnings',
    'insights.detailsPlaceholder': 'Describe what you would like to see in this insight...',
    'insights.requestSuccessTitle': 'Proposal Submitted',
    'insights.requestSuccessMessage': 'Your insight proposal has been submitted to the admin team for review.',
    'insights.requestFailed': 'Failed to submit proposal',
    'insights.requestHistory': 'My Proposals',
    'insights.bannedFromInsights': 'You are currently banned from submitting insight proposals.',
    'insights.report': 'Report',
    'insights.reportInsight': 'Report Insight',
    'insights.reportComment': 'Report Comment',
    'insights.reportReason': 'Please select a reason for reporting',
    'insights.reportSpam': 'Spam',
    'insights.reportHarassment': 'Harassment',
    'insights.reportInappropriate': 'Inappropriate content',
    'insights.reportOther': 'Other',

    // Paywall Screen
    'paywall.badge': 'ALSAIF PRO',
    'paywall.title': 'Accelerate Your Portfolio',
    'paywall.subtitle': 'Join a community of elite investors and get the analysis you need to stay ahead.',
    'paywall.feature1Title': 'Premium Insights',
    'paywall.feature1Desc': 'Unlock exclusive market analysis daily',
    'paywall.feature2Title': 'Expert Groups',
    'paywall.feature2Desc': 'Join professional chat rooms with real-time picks',
    'paywall.feature3Title': 'AI Predictions',
    'paywall.feature3Desc': 'Get data-driven price targets for top stocks',
    'paywall.feature4Title': 'Priority Support',
    'paywall.feature4Desc': 'Direct line to our analyst team for your queries',
    'paywall.secure': 'Secure',
    'paywall.cancelAnytime': 'Cancel Anytime',
    'paywall.verified': 'Verified',
    'paywall.explorePlans': 'Explore Plans',
    'paywall.restore': 'Restore',
    'paywall.terms': 'Terms',
    'paywall.privacy': 'Privacy',

    // Subscription Plans Screen
    'plans.title': 'Subscription Plans',
    'plans.heroTitle': 'Simple, Transparent Pricing',
    'plans.heroSubtitle': 'Choose the plan that fits your investing style.',
    'plans.monthly': 'Monthly',
    'plans.yearly': 'Yearly',
    'plans.save': 'SAVE 20%',
    'plans.perMonth': '/mo',
    'plans.selectPlan': 'Select Plan',
    'plans.mostPopular': 'MOST POPULAR',
    'plans.processing': 'Processing...',
    'plans.goProfessional': 'Go Professional',
    'plans.secureTransactions': 'Secure Transactions',
    'plans.autoRenews': 'Auto-renews',

    // Settings Screen
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.changePassword': 'Change Password',
    'settings.biometricLogin': 'Biometric Login',
    'settings.appPreferences': 'App Preferences',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.dark': 'Dark',
    'settings.light': 'Light',
    'settings.auto': 'Auto',
    'settings.chatSettings': 'Chat Settings',
    'settings.muteGroupChats': 'Mute Group Chats',
    'settings.readReceipts': 'Read Receipts',
    'settings.accessibility': 'Accessibility',
    'settings.textSize': 'Text Size',
    'settings.default': 'Default',
    'settings.highContrast': 'High Contrast',
    'settings.reduceMotion': 'Reduce Motion',
    'settings.reduceMotionMessage': 'Reduced motion will be available in a future update',
    'settings.security': 'Security',
    'settings.activeSessions': 'Active Sessions',
    'settings.devices': 'devices',
    'settings.logoutAllDevices': 'Logout All Devices',
    'settings.notifications': 'Notifications',
    'settings.notificationPreferences': 'Notification Preferences',
    'settings.pushNotifications': 'Push Notifications',
    'settings.emailNotifications': 'Email Notifications',
    'settings.privacyData': 'Privacy & Data',
    'settings.downloadMyData': 'Download My Data',
    'settings.profileVisibility': 'Profile Visibility',
    'settings.public': 'Public',
    'settings.dataPrivacy': 'Data & Privacy',
    'settings.about': 'About',
    'settings.version': 'Version',
    'settings.termsOfService': 'Terms of Service',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.helpSupport': 'Help & Support',
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    'settings.accountDeletionScheduled': 'Account Deletion Scheduled',
    'settings.accountWillBeDeleted': 'Your account will be deleted in {days} day(s) ({date})',
    'settings.cancelDeletion': 'Cancel Deletion',
    'settings.languageUpdated': 'Language updated successfully',
    'settings.themeUpdated': 'Theme updated successfully',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmNewPassword': 'Confirm New Password',
    'settings.selectLanguage': 'Select Language',
    'settings.selectTheme': 'Select Theme',
    'settings.deleteAccountTitle': 'Delete Account',
    'settings.deleteAccountWarning': 'This action cannot be undone. All your data will be permanently deleted.',
    'settings.deleteAccountConfirmation': 'Enter your password to confirm',
    'settings.confirmDeletion': 'Confirm Deletion',
    'settings.currentDevice': 'Current device',
    'settings.revoke': 'Revoke',
    'settings.lastActive': 'Last active',
    'settings.mobile': 'Mobile',
    'settings.tablet': 'Tablet',
    'settings.desktop': 'Desktop',
    'settings.unknown': 'Unknown',
    'settings.chrome': 'Chrome',
    'settings.safari': 'Safari',
    'settings.firefox': 'Firefox',
    'settings.edge': 'Edge',
    'settings.windows': 'Windows',
    'settings.macos': 'macOS',
    'settings.linux': 'Linux',
    'settings.android': 'Android',
    'settings.ios': 'iOS',
    'settings.revokeSession': 'Revoke Session',
    'settings.revokeSessionMessage': 'Revoke session on {device} ({browser})?',
    'settings.logoutAllDevicesTitle': 'Logout from All Devices',
    'settings.logoutAllDevicesConfirm': 'This will log you out from all devices including this one. You will need to log in again.',
    'settings.securityAlerts': 'Security Alerts',
    'settings.accountActivity': 'Account Activity',
    'settings.policyChanges': 'Policy Changes',
    'settings.renewals': 'Renewals',
    'settings.cancellations': 'Cancellations',
    'settings.upgrades': 'Upgrades',
    'settings.newInsights': 'New Insights',
    'settings.savedContent': 'Saved Content',
    'settings.likes': 'Likes',
    'settings.comments': 'Comments',
    'settings.follows': 'Follows',
    'settings.promotions': 'Promotions',
    'settings.newsletter': 'Newsletter',
    'settings.subscription': 'Subscription',
    'settings.content': 'Content',
    'settings.engagement': 'Engagement',
    'settings.marketing': 'Marketing',
    'settings.system': 'System',
    'settings.reasonOptional': 'Reason for leaving (optional)',


    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.users': 'Users',
    'admin.insights': 'Insights',
    'admin.subscriptions': 'Subscriptions',
    'admin.broadcast': 'Broadcast',
    'admin.auditLogs': 'Audit Logs',
    'admin.analytics': 'Analytics',
    'admin.revenue': 'Revenue',
    'admin.description': 'Description',
    'admin.descripation': 'Description',
    'admin.scheduler': 'Scheduler',
    'admin.moderation': 'Moderation',
    'admin.subscriptionPlans': 'Subscription Plans',
    'admin.discountCodes': 'Discount Codes',
    'admin.bannerManagement': 'Banner Management',
    'admin.manageHomeBanners': 'Manage home screen carousel banners',
    'admin.createBanner': 'Create Banner',
    'admin.editBanner': 'Edit Banner',
    'admin.deleteBanner': 'Delete Banner',
    'admin.bannerTitle': 'Banner Title',
    'admin.bannerImageUrl': 'Image URL',
    'admin.bannerLinkUrl': 'Action Link URL',
    'admin.partnerName': 'Partner Name',
    'admin.displayOrder': 'Display Order',
    'admin.tabVisibility': 'Tab Visibility',

    // Admin Stats
    'admin.totalUsers': 'Total Users',
    'admin.premiumSubscribers': 'Premium Subscribers',
    'admin.totalInsights': 'Total Insights',
    'admin.subscriptionRevenue': 'Subscription Revenue',
    'admin.active': 'active',
    'admin.inactive': 'inactive',
    'admin.activeSubs': 'active subs',
    'admin.published': 'published',

    // Admin Actions
    'admin.quickActions': 'Quick Actions',
    'admin.allSections': 'All Sections',
    'admin.createInsight': 'Create Insight',
    'admin.manageUsers': 'Manage Users',
    'admin.sendBroadcast': 'Send Broadcast',
    'admin.viewAnalytics': 'View Analytics',
    'admin.moderationQueue': 'Moderation Queue',
    'admin.flaggedContent': 'Flagged Content',
    'admin.pendingReview': 'Pending Review',
    'admin.flaggedItems': 'Flagged Items',
    'admin.criticalFlags': 'Critical Flags',
    'admin.resolvedToday': 'Resolved Today',
    'admin.searchQueue': 'Search queue...',
    'admin.searchFlags': 'Search flags...',
    'admin.emptyQueue': 'No Pending Review',
    'admin.noFlaggedContent': 'No Flagged Content',
    'admin.moderationClear': 'All content has been reviewed',
    'admin.takeAction': 'Take Action',
    'admin.moderationHistory': 'Moderation History',
    'admin.noSubscriptionPlans': 'No Subscription Plans',
    'admin.noSubscriptionPlansMessage': 'Create subscription plans to monetize your app',
    'admin.createPlan': 'Create Plan',
    'admin.planActions': 'Plan Actions',
    'admin.planName': 'Plan Name',
    'admin.editPlan': 'Edit Plan',
    'admin.viewSubscribers': 'View Subscribers',
    'admin.deletePlan': 'Delete Plan',
    'admin.deletePlanMessage': 'Are you sure you want to delete this subscription plan?',
    'admin.deactivate': 'Deactivate',
    'admin.activate': 'Activate',
    'admin.planPrice': 'Price',
    'admin.planCurrency': 'Currency',
    'admin.planTier': 'Tier',
    'admin.billingCycle': 'Billing Cycle',
    'admin.quarterly': 'Quarterly',
    'admin.yearly': 'Yearly',
    'admin.features': 'Features',
    'admin.addFeature': 'Add Feature',
    'admin.isFeatured': 'Is Featured',
    'admin.basic': 'Basic',
    'admin.starter': 'Starter',
    'admin.premium': 'Premium',
    'admin.pro': 'Pro',
    'admin.enterprise': 'Enterprise',
    'admin.savePlan': 'Save Plan',
    'admin.approveContent': 'Approve Content',
    'admin.rejectContentLabel': 'Reject Content',
    'admin.removeContentLabel': 'Remove Content',
    'admin.removeMessage': 'Are you sure you want to remove this content?',
    'admin.contactReporter': 'Contact Reporter',
    'admin.status': 'Status',
    'admin.pending': 'Pending',
    'admin.approved': 'Approved',
    'admin.rejected': 'Rejected',
    'admin.resolved': 'Resolved',
    'admin.reports': 'Reports',
    'admin.review': 'Review',
    'admin.noDiscountCodes': 'No Discount Codes',
    'admin.noDiscountCodesMessage': 'Create discount codes to offer special promotions to your users',
    'admin.createCode': 'Create Code',
    'admin.editCode': 'Edit Code',
    'admin.deleteCode': 'Delete Code',
    'admin.deleteCodeMessage': 'Are you sure you want to delete this discount code? This action cannot be undone.',
    'admin.codeLabel': 'Discount Code',
    'admin.codeValue': 'Value',
    'admin.maxUses': 'Max Uses',
    'admin.usage': 'Usage',
    'admin.validUntil': 'Valid Until',
    'admin.applicableTiers': 'Applicable Tiers',
    'admin.codeType': 'Code Type',
    'admin.percentage': 'Percentage',
    'admin.fixedAmount': 'Fixed Amount',
    'admin.freeTrial': 'Free Trial',
    'admin.trialDays': 'Trial Days',
    'admin.codeActions': 'Code Actions',
    'admin.duplicateCode': 'Duplicate Code',
    'admin.saveCode': 'Save Code',
    'admin.expired': 'Expired',
    'admin.valid': 'Valid',
    'admin.insightRequests': 'Insight Proposals',
    'admin.moderateRequest': 'Moderate Proposal',
    'admin.banFromInsights': 'Ban from Insights',
    'admin.bannedFromInsights': 'Banned from Insights',

    // Admin Section Titles
    'admin.userManagement': 'User Management',
    'admin.contentManagement': 'Content Management',
    'admin.notifications': 'Notifications',
    'admin.analyticsDashboard': 'Analytics Dashboard',
    'admin.revenueDashboard': 'Revenue Dashboard',
    'admin.contentScheduler': 'Content Scheduler',
    'admin.contentModeration': 'Content Moderation',

    // Admin Section Descriptions
    'admin.manageUsersRoles': 'Manage users, roles, and permissions',
    'admin.createManageInsights': 'Create and manage insights',
    'admin.viewManageSubscriptions': 'View and manage subscriptions',
    'admin.broadcastNotifications': 'Broadcast notifications to users',
    'admin.viewComprehensiveAnalytics': 'View comprehensive analytics and insights',
    'admin.trackRevenueMRR': 'Track revenue, MRR, ARR, and payments',
    'admin.schedulePublishContent': 'Schedule and publish content',
    'admin.reviewModerateContent': 'Review and moderate user content',
    'admin.manageSubscriptionTiers': 'Manage subscription tiers and pricing',
    'admin.createManageCodes': 'Create and manage promotional codes',

    // Admin User Management
    'admin.searchUsers': 'Search users...',
    'admin.userActions': 'User Actions',
    'admin.suspendUser': 'Suspend User',
    'admin.activateUser': 'Activate User',
    'admin.confirmSuspend': 'Confirm Suspend',
    'admin.confirmSuspendMessage': 'Are you sure you want to suspend this user?',
    'admin.suspend': 'Suspend',
    'admin.premiumDescription': 'Full access to all features',
    'admin.freeDescription': 'Basic features only',
    'admin.allUsers': 'All Users',
    'admin.usersOnly': 'Users Only',
    'admin.admins': 'Admins',
    'admin.superadmins': 'Superadmins',
    'admin.viewDetails': 'View Details',
    'admin.editUser': 'Edit User',
    'admin.deleteUser': 'Delete User',
    'admin.deleteUserMessage': 'Are you sure you want to delete this user? This action cannot be undone.',
    'admin.createUser': 'Create User',
    'admin.updateUser': 'Update User',
    'admin.noUsersFound': 'No Users Found',
    'admin.noUsersMessage': 'Try adjusting your search or filters',
    'admin.name': 'Name',
    'admin.namePlaceholder': 'Enter name...',
    'admin.email': 'Email',
    'admin.emailPlaceholder': 'Enter email...',
    'admin.password': 'Password',
    'admin.passwordPlaceholder': 'Enter password...',
    'admin.role': 'Role',
    'admin.nameRequired': 'Name is required',
    'admin.emailRequired': 'Email is required',
    'admin.passwordRequired': 'Password is required',
    'admin.passwordMinLength': 'Password must be at least 6 characters',
    'admin.searchInsights': 'Search insights...',
    'admin.noInsightsFound': 'No Insights Found',
    'admin.noInsightsMessage': 'Try adjusting your search or filters',
    'admin.editInsight': 'Edit',
    'admin.publishInsight': 'Publish',
    'admin.featureInsight': 'Feature Insight',
    'admin.unfeatureInsight': 'Unfeature Insight',
    'admin.scheduling': 'Scheduling',
    'admin.scheduleInsight': 'Schedule Insight',
    'admin.cancelSchedule': 'Cancel Schedule',
    'admin.scheduledFor': 'Scheduled For',
    'admin.deleteInsight': 'Delete',
    'admin.insightFeatured': 'Insight featured',
    'admin.insightUnfeatured': 'Insight unfeatured',
    'admin.insightPublished': 'Insight published successfully',
    'admin.insightCreated': 'Insight created successfully',
    'admin.insightUpdated': 'Insight updated successfully',
    'admin.insightDeleted': 'Insight deleted successfully',
    'admin.manageInsight': 'Manage',
    'admin.selectAction': 'Select an action',
    'admin.publishConfirm': 'Publish Insight',
    'admin.publishMessage': 'This will make it visible to users.',
    'admin.deleteConfirm': 'Delete Insight',
    'admin.deleteMessage': 'This action cannot be undone.',
    'admin.provideReason': 'Provide a reason (optional)',
    'admin.reasonRequired': 'Reason is required',
    'admin.createInsightTitle': 'Create Insight',
    'admin.updateInsightTitle': 'Update Insight',
    'admin.insightTitle': 'Title',
    'admin.insightTitlePlaceholder': 'Enter insight title...',
    'admin.insightContent': 'Content',
    'admin.insightContentPlaceholder': 'Enter insight content...',
    'admin.insightExcerpt': 'Summary (Optional)',
    'admin.insightExcerptPlaceholder': 'Brief summary...',
    'admin.insightType': 'Type',
    'admin.insightCategory': 'Category',
    'admin.insightTags': 'Tags (comma-separated)',
    'admin.insightTagsPlaceholder': 'e.g. stocks, trading, analysis',
    'admin.validationError': 'Validation Error',
    'admin.titleMinLength': 'Title must be at least 5 characters',
    'admin.titleMaxLength': 'Title must not exceed 200 characters',
    'admin.contentMinLength': 'Content must be at least 20 characters',
    'admin.summaryMaxLength': 'Summary must not exceed 500 characters',
    'admin.failedToCreate': 'Failed to create insight',
    'admin.failedToUpdate': 'Failed to update insight',
    'admin.failedToDelete': 'Failed to delete insight',
    'admin.failedToPublish': 'Failed to publish insight',
    'admin.noInsightSelected': 'No insight selected',
    'admin.deletedByAdmin': 'Deleted by admin',

    // Subscription Management
    'admin.searchSubscriptions': 'Search subscriptions...',
    'admin.noSubscriptionsFound': 'No Subscriptions Found',
    'admin.noSubscriptionsMessage': 'No subscriptions match your filters',
    'admin.grantSubscription': 'Grant Subscription',
    'admin.revokeSubscription': 'Revoke Subscription',
    'admin.manageSubscription': 'Manage Subscription',
    'admin.subscriptionGranted': 'Subscription granted successfully',
    'admin.subscriptionRevoked': 'Subscription revoked successfully',
    'admin.daysRemaining': 'days remaining',
    'admin.ends': 'Ends',
    'admin.autoRenewEnabled': 'Auto-renew enabled',
    'admin.userId': 'User ID',
    'admin.userEmail': 'User Email',
    'admin.userIdPlaceholder': 'Enter user ID...',
    'admin.tier': 'Tier',
    'admin.duration': 'Duration (days)',
    'admin.durationPlaceholder': '30',
    'admin.reason': 'Reason',
    'admin.reasonPlaceholder': 'Explain why this subscription is being granted...',
    'admin.reasonForRevocation': 'Reason for revocation',
    'admin.revocationPlaceholder': 'Explain why this subscription is being revoked...',
    'admin.confirmRevocation': 'Confirm Revocation',
    'admin.userIdRequired': 'User ID is required',
    'admin.durationMinimum': 'Duration must be at least 1 day',
    'admin.onlyActiveCanRevoke': 'Only active subscriptions can be revoked',
    'admin.allSubscriptions': 'All Subscriptions',
    'admin.activeSubscriptions': 'Active',
    'admin.expiredSubscriptions': 'Expired',
    'admin.pendingSubscriptions': 'Pending',

    // Broadcast Notifications
    'admin.sendNotification': 'Send Notification',
    'admin.notificationTitle': 'Title',
    'admin.notificationTitlePlaceholder': 'Enter notification title...',
    'admin.notificationMessage': 'Message',
    'admin.notificationMessagePlaceholder': 'Enter notification message...',
    'admin.targetAudience': 'Target Audience',
    'admin.priority': 'Priority',
    'admin.actionUrl': 'Action URL (Optional)',
    'admin.actionUrlPlaceholder': 'e.g., myapp://insights/123',
    'admin.imageUrl': 'Image URL (Optional)',
    'admin.imageUrlPlaceholder': 'https://...',
    'admin.confirmBroadcast': 'Confirm Broadcast',
    'admin.confirmBroadcastMessage': 'This action cannot be undone.',
    'admin.notificationSent': 'Notification sent successfully',
    'admin.recipientsCount': 'recipients',
    'admin.recentBroadcasts': 'Recent Broadcasts',
    'admin.noBroadcastHistory': 'No Broadcast History',
    'admin.noBroadcastMessage': 'Send your first broadcast notification',
    'admin.filterByRole': 'Filter by Role',
    'admin.filterByStatus': 'Filter by Status',
    'admin.allStatuses': 'All Statuses',
    'admin.sent': 'Sent',
    'admin.by': 'By',
    'admin.recipients': 'Recipients',
    'admin.broadcastSendTo': 'Send notification to',
    'admin.broadcastConfirmSendTo': 'Send notification to',
    'admin.broadcastFormTitleRequired': 'Title is required',
    'admin.broadcastFormTitleMaxLength': 'Title must not exceed 100 characters',
    'admin.broadcastFormMessageRequired': 'Message body is required',
    'admin.broadcastFormMessageMaxLength': 'Body must not exceed 500 characters',

    // Broadcast Targets
    'target.all': 'All Users',
    'target.premium': 'Premium Subscribers',
    'target.basic': 'Basic Users',
    'target.active': 'Recently Active Users',
    'target.admins': 'Administrators',

    // Notification Priorities
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    'priority.urgent': 'Urgent',

    // User Roles
    'role.user': 'User',
    'role.admin': 'Admin',
    'role.superadmin': 'Superadmin',

    // User Tiers
    'tier.basic': 'Basic',
    'tier.starter': 'Starter',
    'tier.premium': 'Premium',
    'tier.pro': 'Pro',
    'tier.enterprise': 'Enterprise',

    // User Statuses
    'status.active': 'Active',
    'status.suspended': 'Suspended',
    'status.pending': 'Pending',
    'status.expired': 'Expired',
    'status.cancelled': 'Cancelled',
    'status.none': 'None',

    // Insight Types
    'type.free': 'Free',
    'type.premium': 'Premium',
    'type.both': 'Both',

    // Insight Statuses
    'status.draft': 'Draft',
    'status.published': 'Published',
    'status.archived': 'Archived',
    'status.under_review': 'Under Review',
    'status.scheduled': 'Scheduled',

    // Insight Categories
    'category.market_analysis': 'General Market Trends',
    'category.trading_tips': 'Trading Tips',
    'category.technical_analysis': 'Stock Price Patterns',
    'category.fundamental_analysis': 'Company Value & Health',
    'category.risk_management': 'Protecting Your Money',
    'category.strategy': 'Strategy',
    'category.news': 'News',
    'category.education': 'Education',
    'category.other': 'Other',

    // Insight Filter Options
    'filter.all': 'All',
    'filter.premium': 'Premium',
    'filter.free': 'Free',
    'filter.trending': 'Trending',
    'filter.featured': 'Featured',
    'filter.published': 'Published',
    'filter.drafts': 'Drafts',
    'filter.scheduled': 'Scheduled',

    // Admin Analytics
    'admin.daily': 'Daily',
    'admin.weekly': 'Weekly',
    'admin.monthly': 'Monthly',
    'admin.dateRange': 'Date Range',
    'admin.keyMetrics': 'Key Metrics',
    'admin.activeUsers': 'Active Users',
    'admin.newUsers': 'New Users',
    'admin.avgSession': 'Avg Session',
    'admin.userGrowth': 'User Growth',
    'admin.freeTier': 'Free Tier',
    'admin.basicTier': 'Basic Tier',
    'admin.premiumTier': 'Premium Tier',
    'admin.proTier': 'Pro Tier',
    'admin.conversionFunnel': 'Conversion Funnel',
    'admin.deviceDistribution': 'Device Distribution',
    'admin.featureUsage': 'Feature Usage',
    'admin.topContent': 'Top Performing Content',
    'admin.views': 'views',
    'admin.likes': 'likes',
    'admin.retentionCohorts': 'Retention Cohorts',
    'admin.geoDistribution': 'Geographic Distribution',
    'admin.country': 'Country',
    'admin.mrr': 'MRR',
    'admin.arr': 'ARR',
    'admin.arpu': 'ARPU',
    'admin.ltv': 'LTV',
    'admin.churnRate': 'Churn Rate',
    'admin.revenueGrowth': 'Revenue Growth',
    'admin.revenueForecast': 'Revenue Forecast',
    'admin.paymentMethods': 'Payment Methods',
    'admin.failedPayments': 'Failed Payments',
    'admin.ltvCac': 'LTV:CAC Ratio',
    'admin.revenueByTier': 'Revenue by Tier',
    'admin.tabOverview': 'Overview',
    'admin.tabEngagement': 'Engagement',
    'admin.tabRevenue': 'Revenue',
    'admin.tabAudience': 'Audience',
    'admin.vsLastPeriod': 'vs last period',
    'admin.topContentFull': 'Top Performing Content (All-Time)',

    // Notifications Screen
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark All Read',
    'notifications.unread': '{count} unread',
    'notifications.emptyTitle': 'No Notifications Yet',
    'notifications.emptySubtitle': "You're all caught up! We'll notify you when something important happens.",
    'notifications.errorTitle': 'Connection Error',
    'notifications.errorSubtitle': 'Unable to load notifications. Please check your connection.',
    'notifications.retry': 'Retry',
    'notifications.category.all': 'All',
    'notifications.category.subscription': 'Subscription',
    'notifications.category.content': 'Content',
    'notifications.category.engagement': 'Engagement',
    'notifications.category.premium': 'Premium',
    'notifications.category.system': 'System',
    'notifications.group.today': 'Today',
    'notifications.group.yesterday': 'Yesterday',
    'notifications.group.thisWeek': 'This Week',
    'notifications.group.older': 'Older',
    'notifications.dismiss': 'Dismiss',
    'notifications.dismissConfirm': 'Are you sure you want to dismiss this notification?',
    'notifications.noUnread': 'No Unread Notifications',
    'notifications.allReadMessage': 'All notifications are already read.',
    'notifications.markAllReadConfirm': 'Mark all {count} notifications as read?',

    // Notification Event Titles
    'notifications.event.subscription:created': 'Subscription Active',
    'notifications.event.subscription:upgraded': 'Plan Upgraded',
    'notifications.event.subscription:downgraded': 'Plan Changed',
    'notifications.event.subscription:renewed': 'Subscription Renewed',
    'notifications.event.subscription:cancelled': 'Subscription Cancelled',
    'notifications.event.subscription:expired': 'Subscription Expired',
    'notifications.event.subscription:expiring-soon': 'Subscription Expiring Soon',
    'notifications.event.subscription:payment-failed': 'Payment Failed',
    'notifications.event.subscription:trial-started': 'Trial Started',
    'notifications.event.subscription:trial-ending-soon': 'Trial Ending Soon',
    'notifications.event.subscription:trial-ended': 'Trial Ended',
    'notifications.event.insight:published': 'New Insight Available',
    'notifications.event.insight:premium-published': 'Premium Insight Available',
    'notifications.event.insight:featured': 'Featured Content',
    'notifications.event.insight:trending': 'Trending Now',
    'notifications.event.insight:saved': 'Content Saved',
    'notifications.event.engagement:insight-liked': 'Someone liked your insight',
    'notifications.event.engagement:insight-commented': 'New comment',
    'notifications.event.engagement:user-followed': 'New follower',
    'notifications.event.engagement:user-mentioned': 'You were mentioned',
    'notifications.event.engagement:comment-replied': 'Reply to your comment',
    'notifications.event.premium:content-available': 'Exclusive Content',
    'notifications.event.premium:early-access': 'Early Access',
    'notifications.event.premium:special-offer': 'Special Offer',
    'notifications.event.premium:webinar': 'Webinar Invitation',
    'notifications.event.system:welcome': 'Welcome to Elsaif Capital',
    'notifications.event.system:security-alert': 'Security Alert',
    'notifications.event.system:account-activity': 'Account Activity',
    'notifications.event.system:policy-update': 'Policy Update',
    'notifications.event.system:maintenance': 'Scheduled Maintenance',
    'notifications.event.system:app-update': 'Update Available',
    'notifications.event.marketing:promotion': 'Special Promotion',
    'notifications.event.marketing:newsletter': 'Newsletter',
    'notifications.event.marketing:survey': 'Your Feedback Needed',
    'notifications.event.marketing:announcement': 'Announcement',

    // Notification Time
    'notifications.time.justNow': 'Just now',
    'notifications.time.minsAgo': '{count}m ago',
    'notifications.time.hoursAgo': '{count}h ago',
    'notifications.time.daysAgo': '{count}d ago',


    // Legal
    'legal.terms.title': 'Terms and Conditions',
    'legal.terms.header': 'Terms and Conditions for Application Use',
    'legal.terms.sec1Title': '1. Nature of Service',
    'legal.terms.sec1Content': 'The application provides informational and analytical content and general recommendations related to financial markets for educational purposes only. It is not considered investment advice, an official recommendation, or a guarantee of profits.',
    'legal.terms.sec2Title': '2. Disclaimer',
    'legal.terms.sec2Content1': 'The user bears full responsibility for all their investment decisions.',
    'legal.terms.sec2Content2': 'The application, its developers, or those in charge of it do not bear any responsibility for any direct or indirect financial losses resulting from the use of the content.',
    'legal.terms.sec2Content3': 'The user understands that investing in financial markets involves risks and may lead to full or partial loss of capital.',
    'legal.terms.sec3Title': '3. App Store Non-Responsibility',
    'legal.terms.sec3Content1': 'Google Play Store and Apple App Store are not parties to these terms and do not bear any responsibility for the content of the application or the services provided through it.',
    'legal.terms.sec3Content2': 'Any claims, disputes, or liabilities arising from the use of the application are between the user and the application management only.',
    'legal.terms.sec4Title': '4. User Obligations',
    'legal.terms.sec4Content1': 'The user is committed to using the application for personal and legal use only.',
    'legal.terms.sec4Content2': 'The user is committed not to misuse the application or republish its content by any means without prior permission.',
    'legal.terms.sec4Content3': 'The user acknowledges not to rely entirely on the application content without consulting a licensed financial specialist when needed.',
    'legal.terms.sec5Title': '5. Subscriptions and Payments',
    'legal.terms.sec5Content1': 'Paid subscriptions are managed through Google Play or Apple App Store according to each store\'s policies.',
    'legal.terms.sec5Content2': 'Paid fees are non-refundable after activating the subscription, except according to the refund policies of the used store.',
    'legal.terms.sec5Content3': 'The user is responsible for managing or cancelling the subscription through their account in the store.',
    'legal.terms.sec6Title': '6. Intellectual Property Rights',
    'legal.terms.sec6Content': 'All intellectual rights related to the application and its content, including texts, analyses, designs, and software, are exclusively owned by the application management, and it is prohibited to copy or use them without prior written consent.',
    'legal.terms.sec7Title': '7. Suspension or Suspension of Account',
    'legal.terms.sec7Content': 'The application management has the right to suspend or stop the user\'s account in case of violation of these terms or misuse, without any obligation to compensate.',
    'legal.terms.sec8Title': '8. Amendment of Terms',
    'legal.terms.sec8Content': 'The application reserves the right to modify or update these terms at any time. The user\'s continued use of the application after publishing the amendments is considered explicit consent to them.',
    'legal.terms.sec9Title': '9. Governing Law and Jurisdiction',
    'legal.terms.sec9Content': 'These terms are governed and interpreted according to the laws of the United Arab Emirates, and the state courts have jurisdiction over any dispute arising from them.',
    'legal.terms.sec10Title': '10. Consent',
    'legal.terms.sec10Content': 'By using the application or creating an account, you acknowledge that you have read, understood, and fully agreed to these terms.',
  },
  ar: {
    // Splash Screen
    'splash.initializing': 'جاري التحميل',

    // Login Screen
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'بوابة وصول آمنة للموظفين\nالمصرح لهم فقط.',
    'login.email': 'عنوان البريد الإلكتروني',
    'login.emailPlaceholder': 'you@Alsaif-analysis.com',
    'login.password': 'كلمة المرور',
    'login.passwordPlaceholder': 'أدخل كلمة المرور',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.loginButton': 'تسجيل الدخول',
    'login.secureConnection': 'اتصال آمن',
    'login.faceId': 'التعرف على الوجه',
    'login.touchId': 'بصمة الإصبع',
    'login.biometricLogin': 'تسجيل الدخول البيومتري',
    'login.encryption': 'محمي بتشفير SSL 256 بت.\nالإصدار 4.2.0 (البناء 2024.10)',
    'login.noAccount': 'ليس لديك حساب؟ ',
    'login.signUp': 'سجل الآن',

    // Register Screen
    'register.title': 'أنشئ حسابك',
    'register.subtitle': 'احصل على توصية ذكية للأسهم\nوبيانات السوق في الوقت الفعلي.',
    'register.fullName': 'الاسم الكامل',
    'register.fullNamePlaceholder': 'مثال: أحمد محمد',
    'register.email': 'عنوان البريد الإلكتروني',
    'register.emailPlaceholder': 'name@example.com',
    'register.password': 'كلمة المرور',
    'register.passwordPlaceholder': 'أدخل كلمة المرور',
    'register.confirmPassword': 'تأكيد كلمة المرور',
    'register.confirmPasswordPlaceholder': 'أعد إدخال كلمة المرور',
    'register.nationality': 'الجنسية',
    'register.nationalityPlaceholder': 'أدخل جنسيتك',
    'register.passwordStrength': 'قوة كلمة المرور:',
    'register.weak': 'ضعيفة',
    'register.medium': 'متوسطة',
    'register.strong': 'قوية',
    'register.agreeToTerms': 'أوافق على ',
    'register.termsOfService': 'شروط الخدمة',
    'register.and': ' و ',
    'register.privacyPolicy': 'سياسة الخصوصية',
    'register.signUpButton': 'إنشاء حساب',
    'register.alreadyHaveAccount': 'لديك حساب بالفعل؟ ',
    'register.logIn': 'تسجيل الدخول',

    // Forgot Password Screen
    'forgotPassword.title': 'هل نسيت كلمة السر؟',
    'forgotPassword.subtitle': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك تعليمات لإعادة تعيين كلمة المرور الخاصة بك',
    'forgotPassword.emailPlaceholder': 'you@example.com',
    'forgotPassword.sendLink': 'إرسال رابط إعادة التعيين',
    'forgotPassword.successTitle': 'تم إرسال البريد الإلكتروني!',
    'forgotPassword.successSubtitle': 'تحقق من بريدك الإلكتروني للحصول على تعليمات إعادة التعيين',
    'forgotPassword.successMessage': 'لقد أرسلنا تعليمات إعادة تعيين كلمة المرور إلى',
    'forgotPassword.resendText': 'لم يصلك البريد الإلكتروني؟ إعادة إرسال',
    'forgotPassword.rememberPassword': 'هل تتذكر كلمة المرور؟ ',
    'forgotPassword.backToLogin': 'العودة لتسجيل الدخول',

    // Reset Password Screen
    'resetPassword.title1': 'إعادة تعيين كلمة المرور',
    'resetPassword.successTitle1': 'تمت إعادة تعيين كلمة المرور!',
    'resetPassword.subtitle': 'أدخل رمز التحقق المرسل إلى',
    'resetPassword.successSubtitle': 'تمت إعادة تعيين كلمة المرور الخاصة بك بنجاح',
    'resetPassword.allSet': 'كل شيء جاهز!',
    'resetPassword.allSetSubtitle': 'يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة',
    'resetPassword.verificationCode': 'رمز التحقق',
    'resetPassword.codePlaceholder': '000000',
    'resetPassword.codeHelper': 'أدخل الرمز المكون من 6 أرقام المرسل إلى بريدك الإلكتروني',
    'resetPassword.newPassword': 'كلمة السر الجديدة',
    'resetPassword.passwordPlaceholder': 'أنشئ كلمة مرور قوية',
    'resetPassword.passwordRequirementsMet': '✓ كلمة المرور تستوفي جميع المتطلبات',
    'resetPassword.confirmPassword': 'تأكيد كلمة المرور',
    'resetPassword.confirmPlaceholder': 'أعد إدخال كلمة المرور الخاصة بك',
    'resetPassword.resetButton': 'إعادة تعيين كلمة المرور',

    // Chat List Screen
    'chatList.title': 'المحادثات',
    'chatList.searchPlaceholder': 'ابحث عن مستشار أو رمز...',
    'chatList.filterAll': 'الكل',
    'chatList.filterUnread': 'غير مقروء',
    'chatList.filterPremium': 'مميز',
    'chatList.filterGroups': 'المجموعات',
    'chatList.pinned': 'مثبت',
    'chatList.recent': 'حديث',
    'chatList.loadingConversations': 'جاري تحميل المحادثات...',
    'chatList.noConversations': 'لا توجد محادثات',
    'chatList.noConversationsMessage': 'ابدأ محادثة للتواصل مع المستشارين والمجموعات.',
    'chatList.noResults': 'لا توجد نتائج',
    'chatList.noResultsMessage': 'حاول تعديل البحث أو الفلاتر.',
    'chatList.errorTitle': 'خطأ في الاتصال',
    'chatList.errorMessage': 'تعذر تحميل المحادثات. يرجى التحقق من اتصالك.',
    'chatList.tryAgain': 'حاول مرة أخرى',
    'chatList.newChat': 'دردشة جديدة',
    'chatList.noMessages': 'لا توجد رسائل بعد',
    'chatList.searchUsers': 'بحث عن مستخدمين بالاسم أو البريد الإلكتروني...',
    'chatList.startTyping': 'ابدأ الكتابة للبحث عن مستخدمين',
    'chatList.noUsersFound': 'لم يتم العثور على مستخدمين',
    'chatList.startingChatWith': 'بدء دردشة مع',
    'chatList.initialMessagePlaceholder': 'اكتب رسالة أولية (اختياري)...',
    'chatList.startChat': 'بدء المحادثة',
    'chatList.createError': 'فشل إنشاء المحادثة',
    'chatList.manageChat': 'إدارة المحادثة',
    'chatList.archive': 'أرشفة',
    'chatList.delete': 'حذف',
    'chatList.block': 'حظر',

    // Conversation Screen
    'conversation.typeMessage': 'اكتب رسالة...',
    'conversation.send': 'إرسال',
    'conversation.today': 'اليوم',
    'conversation.yesterday': 'الأمس',
    'conversation.edited': 'معدلة',
    'conversation.deleted': 'تم حذف هذه الرسالة',
    'conversation.noMessages': 'لا توجد رسائل بعد',
    'conversation.startConversation': 'ابدأ محادثة',
    'conversation.loading': 'جاري تحميل الرسائل...',
    'conversation.retry': 'إعادة المحاولة',
    'conversation.failed': 'فشل الإرسال',
    'conversation.sending': 'جاري الإرسال...',
    'conversation.sent': 'تم الإرسال',
    'conversation.delivered': 'تم التوصيل',
    'conversation.read': 'تمت القراءة',
    'conversation.online': 'متصل',
    'conversation.offline': 'غير متصل',
    'conversation.typing': 'يكتب...',
    'conversation.participants': '{count} عضو',
    'conversation.reply': 'رد',
    'conversation.edit': 'تعديل',
    'conversation.delete': 'حذف',
    'conversation.forward': 'إعادة توجيه',
    'conversation.pin': 'تثبيت',
    'conversation.unpin': 'إلغاء التثبيت',
    'conversation.copy': 'نسخ',
    'conversation.pinned': 'مثبتة',
    'conversation.forwarded': 'محول من',
    'conversation.editMessage': 'تعديل الرسالة',
    'conversation.replyTo': 'الرد على',
    'conversation.editYourMessage': 'عدل رسالتك...',
    'conversation.typeReply': 'اكتب ردك...',
    'conversation.cannotSendMessages': 'لا يمكنك إرسال رسائل في هذه المحادثة',
    'conversation.pinnedMessages': 'رسالة مثبتة',
    'conversation.peopleTyping': 'أشخاص يكتبون...',
    'conversation.groupChat': 'مجموعة دردشة',
    'conversation.chat': 'دردشة',
    'conversation.editing': 'تعديل',
    'conversation.replyingTo': 'الرد على',
    'conversation.deleteMessage': 'حذف الرسالة',
    'conversation.deleteConfirm': 'هل أنت متأكد أنك تريد حذف هذه الرسالة؟ لا يمكن التراجع عن هذا الإجراء.',

    // Chat Settings
    'chat.settings.title': 'إعدادات المحادثة',
    'chat.settings.adminControls': 'تحكم المسؤولين',
    'chat.settings.onlyAdminsCanSend': 'المسؤولون فقط يمكنهم الإرسال',
    'chat.settings.onlyAdminsCanSendDescription': 'فقط المسؤولون والأعضاء المسموح لهم يمكنهم إرسال الرسائل',
    'chat.settings.yourPermissions': 'صلاحياتك',
    'chat.settings.youCanSend': 'يمكنك إرسال الرسائل',
    'chat.settings.youCannotSend': 'لا يمكنك إرسال الرسائل',
    'chat.settings.youAreAdmin': 'أنت مسؤول',
    'chat.settings.youAreMember': 'أنت عضو',
    'chat.settings.members': 'الأعضاء',
    'chat.settings.memberCount': '{count} عضو',
    'chat.settings.admin': 'مسؤول',
    'chat.settings.canSend': 'يمكنه الإرسال',
    'chat.settings.kickTitle': 'إزالة العضو',
    'chat.settings.kickConfirm': 'إزالة {name} من هذه المجموعة؟',
    'chat.settings.kick': 'إزالة',
    'chat.settings.updateFailed': 'فشل تحديث الإعدادات',
    'chat.settings.grantFailed': 'فشل منح الصلاحية',
    'chat.settings.revokeFailed': 'فشل إلغاء الصلاحية',
    'chat.settings.kickFailed': 'فشل إزالة العضو',
    'chat.settings.premiumGroup': 'الأعضاء المميزون',
    'chat.settings.communityGroup': 'مجموعة المجتمع',

    // Common
    'common.appName': 'السيف للتحليلات',
    'common.ad': 'إعلان',
    'common.tagline': 'قرارات أذكى. عوائد أعلى.',
    'common.settings': 'الإعدادات',
    'common.theme': 'المظهر',
    'common.language': 'اللغة',
    'common.dark': 'داكن',
    'common.light': 'فاتح',
    'common.all': 'الكل',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.success': 'نجح',
    'common.comingSoon': 'قريبًا',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.retry': 'إعادة المحاولة',
    'common.author': 'كاتب غير معروف',
    'common.details': 'التفاصيل',
    'common.on': 'على',
    'common.loadMore': 'تحميل المزيد',
    'common.seeAll': 'عرض الكل',

    // Time
    'time.justNow': 'الآن',
    'time.minutesAgo': 'منذ {count} دقيقة',
    'time.hoursAgo': 'منذ {count} ساعة',
    'time.daysAgo': 'منذ {count} يوم',
    'time.weeksAgo': 'منذ {count} أسبوع',
    'time.monthsAgo': 'منذ {count} شهر',
    'time.readTime': 'قراءة {count} دقيقة',

    // Bottom Tab Navigation
    'tabs.home': 'الرئيسية',
    'tabs.chat': 'المحادثات',
    'tabs.market': 'السوق',
    'tabs.profile': 'الملف الشخصي',
    'tabs.admin': 'الإدارة',

    // Market Screen
    'market.title': 'بيانات السوق',
    'market.dubai': 'دبي',
    'market.abuDhabi': 'أبو ظبي',
    'market.selectMarketPrompt': 'اختر سوقاً للاستكشاف',
    'market.noData': 'لا توجد بيانات متاحة',
    'market.open': 'الافتتاح',
    'market.high': 'الأعلى',
    'market.low': 'الأدنى',
    'market.prevClose': 'الإغلاق السابق',
    'market.volume': 'الحجم',
    'market.priceHistory': 'سجل الأسعار',

    // Profile Screen
    'profile.title': 'الملف الشخصي',
    'profile.user': 'مستخدم',
    'profile.loading': 'جاري تحميل الملف الشخصي...',
    'profile.memberSince': 'عضو منذ',
    'profile.preferences': 'التفضيلات',
    'profile.darkMode': 'الوضع الداكن',
    'profile.darkModeDesc': 'تبديل السمة الداكنة',
    'profile.language': 'اللغة',
    'profile.subscription': 'الاشتراك',
    'profile.premium': 'مميز',
    'profile.free': 'مجاني',
    'profile.premiumPlan': 'الخطة المميزة',
    'profile.freePlan': 'الخطة المجانية',
    'profile.active': 'نشط',
    'profile.renewsOn': 'يتجدد في',
    'profile.autoRenewal': 'التجديد التلقائي مفعل',
    'profile.manageSubscription': 'إدارة الاشتراك',
    'profile.upgradeToPremium': 'الترقية إلى المميز',
    'profile.actions': 'الإجراءات',
    'profile.logout': 'تسجيل الخروج',
    'profile.logoutConfirm': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    'profile.premiumDescription': 'الوصول إلى جميع التوصية والأدوات المميزة',
    'profile.freeDescription': 'وصول محدود للتوصية',
    'profile.expiresOn': 'ينتهي في',
    'profile.account': 'الحساب',
    'profile.security': 'الأمان',
    'profile.support': 'الدعم',
    'profile.privacy': 'الخصوصية، الشروط والأحكام',
    'profile.deleteAccount': 'حذف الحساب',
    'profile.logoutTitle': 'تسجيل الخروج',
    'profile.logoutMessage': 'هل أنت متأكد من تسجيل الخروج؟',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.name': 'الاسم',
    'profile.enterName': 'أدخل اسمك',
    'profile.avatarUrl': 'رابط الصورة الشخصية (اختياري)',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.error': 'خطأ',
    'profile.success': 'نجاح',
    'profile.nameRequired': 'الاسم لا يمكن أن يكون فارغًا',
    'profile.nameMinLength': 'يجب أن يكون الاسم حرفين على الأقل',
    'profile.nameMaxLength': 'لا يمكن أن يتجاوز الاسم 50 حرفًا',
    'profile.profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
    'profile.updateFailed': 'فشل تحديث الملف الشخصي',
    'profile.comingSoon': 'قريبًا',
    'profile.themeToggleComingSoon': 'سيكون تبديل السمة متاحًا قريبًا!',
    'profile.themeChanged': 'تم تغيير السمة',
    'profile.themeChangedMessage': 'تم تحديث السمة بنجاح!',
    'profile.languageChanged': 'تم تغيير اللغة',
    'profile.languageChangedMessage': 'سيتم إعادة تشغيل التطبيق لتطبيق تغييرات اللغة.',

    // Insights Screen
    'insights.title': 'التوصية',
    'insights.freeInsights': 'توصية مجانية',
    'insights.premiumInsights': 'توصية مميزة',
    'insights.noInsights': 'لا توجد توصية متاحة',
    'insights.noInsightsMessage': 'عد لاحقًا لمزيد من التحديثات.',
    'insights.loading': 'جاري تحميل التوصية...',
    'insights.details': 'تفاصيل التوصية',
    'insights.comments': 'التعليقات',
    'insights.noComments': 'لا توجد تعليقات بعد',
    'insights.loadMoreComments': 'تحميل المزيد من التعليقات',
    'insights.addComment': 'أضف تعليقاً...',
    'insights.loadingInsight': 'جاري تحميل التوصية...',
    'insights.premiumInsight': 'توصية مميزة',
    'insights.types.free': 'توصية مجانية',
    'insights.types.premium': 'توصية مميزة',
    'insights.premiumMessage': 'هذا التحليل العميق حصري للمشتركين المميزين. احصل على وصول كامل لاستراتيجيات خبرائنا في السوق.',
    'insights.unlockNow': 'فتح الآن',
    'insights.share': 'مشاركة',
    'insights.shareComingSoon': 'ميزة المشاركة ستتوفر قريباً',
    'insights.comment': 'تعليق',
    'insights.commentComingSoon': 'ميزة التعليق ستتوفر قريباً',
    'insights.reply': 'رد',
    'insights.replyingTo': 'الرد على',
    'insights.retry': 'إعادة المحاولة',
    'insights.requestTitle': 'اقتراح توصية',
    'insights.requestDetails': 'تفاصيل التوصية',
    'insights.submitRequest': 'تقديم الاقتراح',
    'insights.requestPlaceholder': 'مثال: تحليل أرباح شركة إنفيديا',
    'insights.detailsPlaceholder': 'صف ما تود رؤيته في هذه التوصية...',
    'insights.requestSuccessTitle': 'تم تقديم الاقتراح',
    'insights.requestSuccessMessage': 'تم إرسال اقتراح التوصية الخاص بك إلى فريق الإدارة للمراجعة.',
    'insights.requestFailed': 'فشل تقديم الاقتراح',
    'insights.requestHistory': 'اقتراحاتي',
    'insights.bannedFromInsights': 'أنت محظور حالياً من تقديم اقتراحات التوصية.',
    'insights.report': 'إبلاغ',
    'insights.reportInsight': 'إبلاغ عن محتوى',
    'insights.reportComment': 'إبلاغ عن تعليق',
    'insights.reportReason': 'يرجى تحديد سبب الإبلاغ',
    'insights.reportSpam': 'محتوى غير مرغوب فيه',
    'insights.reportHarassment': 'تحرش/مضايقة',
    'insights.reportInappropriate': 'محتوى غير لائق',
    'insights.reportOther': 'سبب آخر',

    // Paywall Screen
    'paywall.badge': 'السيف برو',
    'paywall.title': 'سرّع محفظتك الاستثمارية',
    'paywall.subtitle': 'انضم إلى مجتمع من نخبة المستثمرين واحصل على التحليل الذي تحتاجه للبقاء في الصدارة.',
    'paywall.feature1Title': 'توصية مميزة',
    'paywall.feature1Desc': 'افتح تحليلات السوق الحصرية يوميًا',
    'paywall.feature2Title': 'مجموعات الخبراء',
    'paywall.feature2Desc': 'انضم إلى غرف الدردشة الاحترافية مع اختيارات في الوقت الفعلي',
    'paywall.feature3Title': 'توقعات الذكاء الاصطناعي',
    'paywall.feature3Desc': 'احصل على أهداف سعرية مدفوعة بالبيانات لأهم الأسهم',
    'paywall.feature4Title': 'دعم ذو أولوية',
    'paywall.feature4Desc': 'خط مباشر مع فريق المحللين لدينا لاستفساراتك',
    'paywall.secure': 'آمن',
    'paywall.cancelAnytime': 'إلغاء في أي وقت',
    'paywall.verified': 'موثوق',
    'paywall.explorePlans': 'استكشف الخطط',
    'paywall.restore': 'استعادة',
    'paywall.terms': 'الشروط',
    'paywall.privacy': 'الخصوصية',

    // Subscription Plans Screen
    'plans.title': 'خطط الاشتراك',
    'plans.heroTitle': 'تسعير بسيط وشفاف',
    'plans.heroSubtitle': 'اختر الخطة التي تناسب أسلوبك في الاستثمار.',
    'plans.monthly': 'شهري',
    'plans.yearly': 'سنوي',
    'plans.save': 'وفر 20%',
    'plans.perMonth': '/شهريًا',
    'plans.selectPlan': 'اختر الخطة',
    'plans.mostPopular': 'الأكثر رواجًا',
    'plans.processing': 'جاري المعالجة...',
    'plans.goProfessional': 'انتقل للمستوى الاحترافي',
    'plans.secureTransactions': 'عمليات آمنة',
    'plans.autoRenews': 'تجديد تلقائي',

    // Settings Screen
    'settings.title': 'الإعدادات',
    'settings.account': 'الحساب',
    'settings.changePassword': 'تغيير كلمة المرور',
    'settings.biometricLogin': 'تسجيل الدخول البيومتري',
    'settings.appPreferences': 'تفضيلات التطبيق',
    'settings.language': 'اللغة',
    'settings.theme': 'السمة',
    'settings.dark': 'داكن',
    'settings.light': 'فاتح',
    'settings.auto': 'تلقائي',
    'settings.chatSettings': 'إعدادات الدردشة',
    'settings.muteGroupChats': 'كتم المحادثات الجماعية',
    'settings.readReceipts': 'إيصالات القراءة',
    'settings.accessibility': 'إمكانية الوصول',
    'settings.textSize': 'حجم النص',
    'settings.default': 'افتراضي',
    'settings.highContrast': 'تباين عالي',
    'settings.reduceMotion': 'تقليل الحركة',
    'settings.reduceMotionMessage': 'سيكون تقليل الحركة متاحًا في تحديث مستقبلي',
    'settings.security': 'الأمان',
    'settings.activeSessions': 'الجلسات النشطة',
    'settings.devices': 'أجهزة',
    'settings.logoutAllDevices': 'تسجيل الخروج من جميع الأجهزة',
    'settings.notifications': 'الإشعارات',
    'settings.notificationPreferences': 'تفضيلات الإشعارات',
    'settings.pushNotifications': 'الإشعارات الفورية',
    'settings.emailNotifications': 'إشعارات البريد الإلكتروني',
    'settings.privacyData': 'الخصوصية والبيانات',
    'settings.downloadMyData': 'تنزيل بياناتي',
    'settings.profileVisibility': 'توصية الملف الشخصي',
    'settings.public': 'عام',
    'settings.dataPrivacy': 'البيانات والخصوصية',
    'settings.about': 'حول',
    'settings.version': 'الإصدار',
    'settings.termsOfService': 'شروط الخدمة',
    'settings.privacyPolicy': 'سياسة الخصوصية',
    'settings.helpSupport': 'المساعدة والدعم',
    'settings.dangerZone': 'منطقة الخطر',
    'settings.deleteAccount': 'حذف الحساب',
    'settings.accountDeletionScheduled': 'تم جدولة حذف الحساب',
    'settings.accountWillBeDeleted': 'سيتم حذف حسابك في {days} يوم ({date})',
    'settings.cancelDeletion': 'إلغاء الحذف',
    'settings.languageUpdated': 'تم تحديث اللغة بنجاح',
    'settings.themeUpdated': 'تم تحديث السمة بنجاح',
    'settings.currentPassword': 'كلمة المرور الحالية',
    'settings.newPassword': 'كلمة المرور الجديدة',
    'settings.confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
    'settings.selectLanguage': 'اختر اللغة',
    'settings.selectTheme': 'اختر السمة',
    'settings.deleteAccountTitle': 'حذف الحساب',
    'settings.deleteAccountWarning': 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع بياناتك نهائيًا.',
    'settings.deleteAccountConfirmation': 'أدخل كلمة المرور للتأكيد',
    'settings.confirmDeletion': 'تأكيد الحذف',
    'settings.currentDevice': 'الجهاز الحالي',
    'settings.revoke': 'إنهاء',
    'settings.lastActive': 'آخر ظهور',
    'settings.mobile': 'هاتف محمول',
    'settings.tablet': 'جهاز لوحي',
    'settings.desktop': 'كمبيوتر',
    'settings.unknown': 'غير معروف',
    'settings.chrome': 'كروم',
    'settings.safari': 'سافاري',
    'settings.firefox': 'فايرفوكس',
    'settings.edge': 'إيدج',
    'settings.windows': 'ويندوز',
    'settings.macos': 'ماك أو إس',
    'settings.linux': 'لينكس',
    'settings.android': 'أندرويد',
    'settings.ios': 'آي أو إس',
    'settings.revokeSession': 'إلغاء الجلسة',
    'settings.revokeSessionMessage': 'إلغاء الجلسة على {device} ({browser})؟',
    'settings.logoutAllDevicesTitle': 'تسجيل الخروج من جميع الأجهزة',
    'settings.logoutAllDevicesConfirm': 'سيؤدي هذا إلى تسجيل خروجك من جميع الأجهزة بما في ذلك هذا الجهاز. ستحتاج إلى تسجيل الدخول مرة أخرى.',
    'settings.securityAlerts': 'تنبيهات الأمان',
    'settings.accountActivity': 'نشاط الحساب',
    'settings.policyChanges': 'تغييرات السياسة',
    'settings.renewals': 'التجديدات',
    'settings.cancellations': 'الإلغاءات',
    'settings.upgrades': 'الترقيات',
    'settings.newInsights': 'رؤى جديدة',
    'settings.savedContent': 'المحتوى المحفوظ',
    'settings.likes': 'الإعجابات',
    'settings.comments': 'التعليقات',
    'settings.follows': 'المتابعات',
    'settings.promotions': 'العروض الترويجية',
    'settings.newsletter': 'النشرة الإخبارية',
    'settings.subscription': 'الاشتراك',
    'settings.content': 'المحتوى',
    'settings.engagement': 'التفاعل',
    'settings.marketing': 'التسويق',
    'settings.system': 'النظام',
    'settings.reasonOptional': 'سبب المغادرة (اختياري)',

    // Admin Dashboard
    'admin.dashboard': 'لوحة التحكم',
    'admin.users': 'المستخدمون',
    'admin.insights': 'التوصية',
    'admin.subscriptions': 'الاشتراكات',
    'admin.broadcast': 'البث',
    'admin.auditLogs': 'سجلات التدقيق',
    'admin.analytics': 'التحليلات',
    'admin.revenue': 'الإيرادات',
    'admin.description': 'الوصف',
    'admin.descripation': 'الوصف',
    'admin.scheduler': 'الجدولة',
    'admin.moderation': 'الإشراف',
    'admin.moderationHistory': 'سجل الإشراف',
    'admin.noSubscriptionPlans': 'لا توجد خطط اشتراك',
    'admin.noSubscriptionPlansMessage': 'أنشئ خطط اشتراك لتحقيق أرباح من تطبيقك',
    'admin.createPlan': 'إنشاء خطة',
    'admin.planActions': 'إجراءات الخطة',
    'admin.planName': 'اسم الخطة',
    'admin.editPlan': 'تعديل الخطة',
    'admin.viewSubscribers': 'عرض المشتركين',
    'admin.deletePlan': 'حذف الخطة',
    'admin.deletePlanMessage': 'هل أنت متأكد من رغبتك في حذف خطة الاشتراك هذه؟',
    'admin.deactivate': 'تعطيل',
    'admin.activate': 'تفعيل',
    'admin.planPrice': 'السعر',
    'admin.planCurrency': 'العملة',
    'admin.planTier': 'الفئة',
    'admin.billingCycle': 'دورة الفوترة',
    'admin.quarterly': 'ربع سنوي',
    'admin.yearly': 'سنوي',
    'admin.features': 'المميزات',
    'admin.addFeature': 'إضافة ميزة',
    'admin.isFeatured': 'خطة مميزة',
    'admin.basic': 'أساسي',
    'admin.starter': 'مبتدئ',
    'admin.premium': 'مميز',
    'admin.pro': 'احترافي',
    'admin.enterprise': 'شركات',
    'admin.savePlan': 'حفظ الخطة',
    'admin.noDiscountCodes': 'لا توجد أكواد خصم',
    'admin.noDiscountCodesMessage': 'أنشئ أكواد خصم لتقديم عروض خاصة لمستخدميك',
    'admin.createCode': 'إنشاء كود',
    'admin.editCode': 'تعديل الكود',
    'admin.deleteCode': 'حذف الكود',
    'admin.deleteCodeMessage': 'هل أنت متأكد من رغبتك في حذف كود الخصم هذا؟ لا يمكن التراجع عن هذا الإجراء.',
    'admin.codeLabel': 'كود الخصم',
    'admin.codeValue': 'القيمة',
    'admin.maxUses': 'أقصى عدد للاستخدام',
    'admin.usage': 'الاستخدام',
    'admin.validUntil': 'صالح حتى',
    'admin.applicableTiers': 'الفئات المطبقة',
    'admin.codeType': 'نوع الكود',
    'admin.percentage': 'نسبة مئوية',
    'admin.fixedAmount': 'مبلغ ثابت',
    'admin.freeTrial': 'فترة تجريبية',
    'admin.trialDays': 'أيام التجربة',
    'admin.codeActions': 'إجراءات الكود',
    'admin.duplicateCode': 'تكرار الكود',
    'admin.saveCode': 'حفظ الكود',
    'admin.expired': 'منتهي',
    'admin.valid': 'صالح',
    'admin.insightRequests': 'اقتراحات التوصية',
    'admin.moderateRequest': 'الإشراف على الاقتراح',
    'admin.banFromInsights': 'حظر من الاقتراحات',
    'admin.bannedFromInsights': 'محظور من الاقتراحات',
    'admin.subscriptionPlans': 'خطط الاشتراك',
    'admin.discountCodes': 'أكواد الخصم',
    'admin.bannerManagement': 'إدارة البانرات',
    'admin.manageHomeBanners': 'إدارة بانرات الشاشة الرئيسية',
    'admin.createBanner': 'إنشاء بانر',
    'admin.editBanner': 'تعديل البانر',
    'admin.deleteBanner': 'حذف البانر',
    'admin.bannerTitle': 'عنوان البانر',
    'admin.bannerImageUrl': 'رابط الصورة',
    'admin.bannerLinkUrl': 'رابط الإثراء',
    'admin.partnerName': 'اسم الشريك',
    'admin.displayOrder': 'ترتيب العرض',
    'admin.tabVisibility': 'رؤية التبويب',

    // Admin Stats
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.premiumSubscribers': 'المشتركون المميزون',
    'admin.totalInsights': 'إجمالي التوصية',
    'admin.subscriptionRevenue': 'إيرادات الاشتراكات',
    'admin.active': 'نشط',
    'admin.inactive': 'غير نشط',
    'admin.activeSubs': 'اشتراكات نشطة',
    'admin.published': 'منشور',

    // Admin Actions
    'admin.quickActions': 'الإجراءات السريعة',
    'admin.allSections': 'جميع الأقسام',
    'admin.createInsight': 'إنشاء توصية',
    'admin.manageUsers': 'إدارة المستخدمين',
    'admin.sendBroadcast': 'إرسال بث',
    'admin.viewAnalytics': 'عرض التحليلات',
    'admin.moderationQueue': 'طابور المراجعة',
    'admin.flaggedContent': 'المحتوى المبلغ عنه',
    'admin.pendingReview': 'قيد المراجعة',
    'admin.flaggedItems': 'العناصر المبلغ عنها',
    'admin.criticalFlags': 'بلاغات حرجة',
    'admin.resolvedToday': 'تمت حلها اليوم',
    'admin.searchQueue': 'بحث في الطابور...',
    'admin.searchFlags': 'بحث في البلاغات...',
    'admin.emptyQueue': 'لا يوجد محتوى قيد المراجعة',
    'admin.noFlaggedContent': 'لا يوجد محتوى مبلغ عنه',
    'admin.moderationClear': 'تمت مراجعة جميع المحتويات',

    'admin.takeAction': 'اتخذ إجراء',
    'admin.moderationActions': 'إجراءات الإشراف',
    'admin.approveContent': 'الموافقة على المحتوى',
    'admin.rejectContentLabel': 'رفض المحتوى',
    'admin.removeContentLabel': 'إزالة المحتوى',
    'admin.removeMessage': 'هل أنت متأكد من رغبتك في إزالة هذا المحتوى؟',
    'admin.contactReporter': 'اتصل بالمبلغ',
    'admin.status': 'الحالة',
    'admin.pending': 'قيد الانتظار',
    'admin.approved': 'تمت الموافقة',
    'admin.rejected': 'مرفوض',
    'admin.resolved': 'تم حلها',
    'admin.reports': 'بلاغات',
    'admin.review': 'مراجعة',
    // Admin Section Titles
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.contentManagement': 'إدارة المحتوى',
    'admin.notifications': 'الإشعارات',
    'admin.analyticsDashboard': 'لوحة التحليلات',
    'admin.revenueDashboard': 'لوحة الإيرادات',
    'admin.contentScheduler': 'جدولة المحتوى',
    'admin.contentModeration': 'إشراف المحتوى',

    // Admin Section Descriptions
    'admin.manageUsersRoles': 'إدارة المستخدمين والأدوار والصلاحيات',
    'admin.createManageInsights': 'إنشاء وإدارة التوصية',
    'admin.viewManageSubscriptions': 'عرض وإدارة الاشتراكات',
    'admin.broadcastNotifications': 'بث الإشعارات للمستخدمين',
    'admin.viewComprehensiveAnalytics': 'عرض التحليلات والتوصية الشاملة',
    'admin.trackRevenueMRR': 'تتبع الإيرادات والإيرادات الشهرية والسنوية',
    'admin.schedulePublishContent': 'جدولة ونشر المحتوى',
    'admin.reviewModerateContent': 'مراجعة وإشراف محتوى المستخدم',
    'admin.manageSubscriptionTiers': 'إدارة مستويات الاشتراك والأسعار',
    'admin.createManageCodes': 'إنشاء وإدارة رموز الترويج',
    'admin.designNotificationTemplates': 'تصميم قوالب الإشعارات القابلة لإعادة الاستخدام',
    'admin.performBatchOperations': 'تنفيذ العمليات المجمعة على عدة عناصر',

    // Admin User Management
    'admin.searchUsers': 'بحث عن المستخدمين...',
    'admin.userActions': 'إجراءات المستخدم',
    'admin.suspendUser': 'تعليق المستخدم',
    'admin.activateUser': 'تفعيل المستخدم',
    'admin.confirmSuspend': 'تأكيد التعليق',
    'admin.confirmSuspendMessage': 'هل أنت متأكد من تعليق هذا المستخدم؟',
    'admin.suspend': 'تعليق',
    'admin.premiumDescription': 'وصول كامل لجميع الميزات',
    'admin.freeDescription': 'الميزات الأساسية فقط',
    'admin.allUsers': 'جميع المستخدمين',
    'admin.usersOnly': 'مستخدمون فقط',
    'admin.admins': 'المسؤولون',
    'admin.superadmins': 'المسؤولون الرئيسيون',
    'admin.viewDetails': 'عرض التفاصيل',
    'admin.editUser': 'تعديل المستخدم',
    'admin.deleteUser': 'حذف المستخدم',
    'admin.deleteUserMessage': 'هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
    'admin.createUser': 'إنشاء مستخدم',
    'admin.updateUser': 'تحديث المستخدم',
    'admin.noUsersFound': 'لم يتم العثور على مستخدمين',
    'admin.noUsersMessage': 'جرب تعديل البحث أو الفلاتر',
    'admin.name': 'الاسم',
    'admin.namePlaceholder': 'أدخل الاسم...',
    'admin.email': 'البريد الإلكتروني',
    'admin.emailPlaceholder': 'أدخل البريد الإلكتروني...',
    'admin.password': 'كلمة المرور',
    'admin.passwordPlaceholder': 'أدخل كلمة المرور...',
    'admin.role': 'الدور',
    'admin.nameRequired': 'الاسم مطلوب',
    'admin.emailRequired': 'البريد الإلكتروني مطلوب',
    'admin.passwordRequired': 'كلمة المرور مطلوبة',
    'admin.passwordMinLength': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    'admin.searchInsights': 'بحث في التوصية...',
    'admin.noInsightsFound': 'لم يتم العثور على توصية',
    'admin.noInsightsMessage': 'جرب تعديل البحث أو الفلاتر',
    'admin.editInsight': 'تعديل',
    'admin.publishInsight': 'نشر',
    'admin.featureInsight': 'تمييز التوصية',
    'admin.unfeatureInsight': 'إلغاء تمييز التوصية',
    'admin.scheduling': 'الجدولة',
    'admin.scheduleInsight': 'جدولة التوصية',
    'admin.cancelSchedule': 'إلغاء الجدولة',
    'admin.scheduledFor': 'مجدول لـ',
    'admin.deleteInsight': 'حذف',
    'admin.insightFeatured': 'تم تمييز التوصية',
    'admin.insightUnfeatured': 'تم إلغاء تمييز التوصية',
    'admin.insightPublished': 'تم نشر التوصية بنجاح',
    'admin.insightCreated': 'تم إنشاء التوصية بنجاح',
    'admin.insightUpdated': 'تم تحديث التوصية بنجاح',
    'admin.insightDeleted': 'تم حذف التوصية بنجاح',
    'admin.manageInsight': 'إدارة',
    'admin.selectAction': 'اختر إجراء',
    'admin.publishConfirm': 'نشر التوصية',
    'admin.publishMessage': 'سيتم عرضها للمستخدمين.',
    'admin.deleteConfirm': 'حذف التوصية',
    'admin.deleteMessage': 'لا يمكن التراجع عن هذا الإجراء.',
    'admin.provideReason': 'قدم السبب:',
    'admin.reasonRequired': 'السبب مطلوب',
    'admin.createInsightTitle': 'إنشاء توصية',
    'admin.updateInsightTitle': 'تحديث التوصية',
    'admin.insightTitle': 'العنوان',
    'admin.insightTitlePlaceholder': 'أدخل عنوان التوصية...',
    'admin.insightContent': 'المحتوى',
    'admin.insightContentPlaceholder': 'أدخل محتوى التوصية...',
    'admin.insightExcerpt': 'ملخص (اختياري)',
    'admin.insightExcerptPlaceholder': 'ملخص موجز...',
    'admin.insightType': 'النوع',
    'admin.insightCategory': 'الفئة',
    'admin.insightTags': 'الوسوم (مفصولة بفواصل)',
    'admin.insightTagsPlaceholder': 'مثال: أسهم، تداول، تحليل',
    'admin.validationError': 'خطأ في التحقق',
    'admin.titleMinLength': 'يجب أن يكون العنوان 5 أحرف على الأقل',
    'admin.titleMaxLength': 'يجب ألا يتجاوز العنوان 200 حرف',
    'admin.contentMinLength': 'يجب أن يكون المحتوى 20 حرفًا على الأقل',
    'admin.summaryMaxLength': 'يجب ألا يتجاوز الملخص 500 حرف',
    'admin.failedToCreate': 'فشل إنشاء التحليل',
    'admin.failedToUpdate': 'فشل تحديث التحليل',
    'admin.failedToDelete': 'فشل حذف التحليل',
    'admin.failedToPublish': 'فشل نشر التحليل',
    'admin.noInsightSelected': 'لم يتم اختيار تحليل',
    'admin.deletedByAdmin': 'تم الحذف بواسطة المسؤول',

    // Subscription Management
    'admin.searchSubscriptions': 'بحث في الاشتراكات...',
    'admin.noSubscriptionsFound': 'لم يتم العثور على اشتراكات',
    'admin.noSubscriptionsMessage': 'لا توجد اشتراكات تطابق الفلاتر',
    'admin.grantSubscription': 'منح اشتراك',
    'admin.revokeSubscription': 'إلغاء الاشتراك',
    'admin.manageSubscription': 'إدارة الاشتراك',
    'admin.subscriptionGranted': 'تم منح الاشتراك بنجاح',
    'admin.subscriptionRevoked': 'تم إلغاء الاشتراك بنجاح',
    'admin.daysRemaining': 'يوم متبقي',
    'admin.ends': 'ينتهي',
    'admin.autoRenewEnabled': 'التجديد التلقائي مفعل',
    'admin.userId': 'معرف المستخدم',
    'admin.userEmail': 'البريد الإلكتروني للمستخدم',
    'admin.userIdPlaceholder': 'أدخل معرف المستخدم...',
    'admin.tier': 'المستوى',
    'admin.duration': 'المدة (بالأيام)',
    'admin.durationPlaceholder': '30',
    'admin.reason': 'السبب',
    'admin.reasonPlaceholder': 'اشرح سبب منح هذا الاشتراك...',
    'admin.reasonForRevocation': 'سبب الإلغاء',
    'admin.revocationPlaceholder': 'اشرح سبب إلغاء هذا الاشتراك...',
    'admin.confirmRevocation': 'تأكيد الإلغاء',
    'admin.userIdRequired': 'معرف المستخدم مطلوب',
    'admin.durationMinimum': 'يجب أن تكون المدة يوم واحد على الأقل',
    'admin.onlyActiveCanRevoke': 'يمكن إلغاء الاشتراكات النشطة فقط',
    'admin.allSubscriptions': 'جميع الاشتراكات',
    'admin.activeSubscriptions': 'نشطة',
    'admin.expiredSubscriptions': 'منتهية',
    'admin.pendingSubscriptions': 'قيد الانتظار',

    // Broadcast Notifications
    'admin.sendNotification': 'إرسال إشعار',
    'admin.notificationTitle': 'العنوان',
    'admin.notificationTitlePlaceholder': 'أدخل عنوان الإشعار...',
    'admin.notificationMessage': 'الرسالة',
    'admin.notificationMessagePlaceholder': 'أدخل رسالة الإشعار...',
    'admin.targetAudience': 'الجمهور المستهدف',
    'admin.priority': 'الأولوية',
    'admin.actionUrl': 'رابط الإجراء (اختياري)',
    'admin.actionUrlPlaceholder': 'مثال: myapp://insights/123',
    'admin.imageUrl': 'رابط الصورة (اختياري)',
    'admin.imageUrlPlaceholder': 'https://...',
    'admin.confirmBroadcast': 'تأكيد البث',
    'admin.confirmBroadcastMessage': 'لا يمكن التراجع عن هذا الإجراء.',
    'admin.notificationSent': 'تم إرسال الإشعار بنجاح',
    'admin.recipientsCount': 'مستلم',
    'admin.recentBroadcasts': 'البث الأخير',
    'admin.noBroadcastHistory': 'لا يوجد سجل بث',
    'admin.noBroadcastMessage': 'أرسل أول بث إشعار',
    'admin.filterByRole': 'تصفية حسب الرتبة',
    'admin.filterByStatus': 'تصفية حسب الحالة',
    'admin.allStatuses': 'جميع الحالات',
    'admin.sent': 'تم الإرسال',
    'admin.by': 'بواسطة',
    'admin.recipients': 'المستلمون',
    'admin.broadcastSendTo': 'إرسال الإشعار إلى',
    'admin.broadcastConfirmSendTo': 'إرسال الإشعار إلى',
    'admin.broadcastFormTitleRequired': 'العنوان مطلوب',
    'admin.broadcastFormTitleMaxLength': 'يجب ألا يتجاوز العنوان 100 حرف',
    'admin.broadcastFormMessageRequired': 'نص الرسالة مطلوب',
    'admin.broadcastFormMessageMaxLength': 'يجب ألا يتجاوز النص 500 حرف',

    // Broadcast Targets
    'target.all': 'جميع المستخدمين',
    'target.premium': 'المشتركون المميزون',
    'target.basic': 'المستخدمون الأساسيون',
    'target.active': 'المستخدمون النشطون مؤخرًا',
    'target.admins': 'المسؤولون',

    // Notification Priorities
    'priority.low': 'منخفضة',
    'priority.medium': 'متوسطة',
    'priority.high': 'عالية',
    'priority.urgent': 'عاجلة',

    // User Roles
    'role.user': 'مستخدم',
    'role.admin': 'مسؤول',
    'role.superadmin': 'مسؤول رئيسي',

    // User Tiers
    'tier.basic': 'أساسي',
    'tier.starter': 'مبتدئ',
    'tier.premium': 'مميز',
    'tier.pro': 'محترف',
    'tier.enterprise': 'مؤسسي',

    // User Statuses
    'status.active': 'نشط',
    'status.suspended': 'معلق',
    'status.pending': 'قيد الانتظار',
    'status.expired': 'منتهي',
    'status.cancelled': 'ملغي',
    'status.none': 'لا يوجد',

    // Insight Types
    'type.free': 'مجاني',
    'type.premium': 'مميز',
    'type.both': 'الكل',

    // Insight Statuses
    'status.draft': 'مسودة',
    'status.published': 'منشور',
    'status.archived': 'مؤرشف',
    'status.under_review': 'قيد المراجعة',
    'status.scheduled': 'مجدول',

    // Insight Categories
    'category.market_analysis': 'تحليل السوق',
    'category.trading_tips': 'توصية التداول',
    'category.technical_analysis': 'التحليل الفني',
    'category.fundamental_analysis': 'التحليل الأساسي',
    'category.risk_management': 'إدارة المخاطر',
    'category.strategy': 'استراتيجية',
    'category.news': 'أخبار',
    'category.education': 'تعليم',
    'category.other': 'أخرى',

    // Insight Filter Options
    'filter.all': 'الكل',
    'filter.premium': 'مميز',
    'filter.free': 'مجاني',
    'filter.trending': 'شائع',
    'filter.featured': 'مميز',
    'filter.published': 'منشور',
    'filter.drafts': 'مسودات',
    'filter.scheduled': 'مجدول',

    // Admin Analytics
    'admin.daily': 'يومي',
    'admin.weekly': 'أسبوعي',
    'admin.monthly': 'شهري',
    'admin.dateRange': 'نطاق التاريخ',
    'admin.keyMetrics': 'المؤشرات الرئيسية',
    'admin.activeUsers': 'المستخدمون النشطون',
    'admin.newUsers': 'المستخدمون الجدد',
    'admin.avgSession': 'متوسط الجلسة',
    'admin.userGrowth': 'نمو المستخدمين',
    'admin.freeTier': 'الفئة المجانية',
    'admin.basicTier': 'الفئة الأساسية',
    'admin.premiumTier': 'الفئة المميزة',
    'admin.proTier': 'الفئة الاحترافية',
    'admin.conversionFunnel': 'قمع التحويل',
    'admin.deviceDistribution': 'توزيع الأجهزة',
    'admin.featureUsage': 'استخدام الميزات',
    'admin.topContent': 'المحتوى الأكثر أداءً',
    'admin.views': 'مشاهدة',
    'admin.likes': 'إعجاب',
    'admin.retentionCohorts': 'مجموعات الاحتفاظ',
    'admin.geoDistribution': 'التوزيع الجغرافي',
    'admin.country': 'الدولة',
    'admin.mrr': 'العائد الشهري',
    'admin.arr': 'العائد السنوي',
    'admin.arpu': 'متوسط العائد لكل مستخدم',
    'admin.ltv': 'القيمة الدائمة للمستخدم',
    'admin.churnRate': 'معدل التوقف',
    'admin.revenueGrowth': 'نمو الإيرادات',
    'admin.revenueForecast': 'توقعات الإيرادات',
    'admin.paymentMethods': 'طرق الدفع',
    'admin.failedPayments': 'المدفوعات الفاشلة',
    'admin.ltvCac': 'نسبة LTV:CAC',
    'admin.revenueByTier': 'الإيرادات حسب الفئة',
    'admin.tabOverview': 'نظرة عامة',
    'admin.tabEngagement': 'التفاعل',
    'admin.tabRevenue': 'الإيرادات',
    'admin.tabAudience': 'الجمهور',
    'admin.vsLastPeriod': 'مقارنة بالفترة السابقة',
    'admin.topContentFull': 'المحتوى الأكثر أداءً (على الإطلاق)',

    // Notifications Screen
    'notifications.title': 'الإشعارات',
    'notifications.markAllRead': 'تحديد الكل كمقروء',
    'notifications.unread': '{count} غير مقروء',
    'notifications.emptyTitle': 'لا توجد إشعارات بعد',
    'notifications.emptySubtitle': 'أنت مطلع على كل شيء! سنقوم بإخطارك عند حدوث شيء مهم.',
    'notifications.errorTitle': 'خطأ في الاتصال',
    'notifications.errorSubtitle': 'تعذر تحميل الإشعارات. يرجى التحقق من اتصالك.',
    'notifications.retry': 'إعادة المحاولة',
    'notifications.category.all': 'الكل',
    'notifications.category.subscription': 'الاشتراك',
    'notifications.category.content': 'المحتوى',
    'notifications.category.engagement': 'التفاعل',
    'notifications.category.premium': 'مميز',
    'notifications.category.system': 'النظام',
    'notifications.group.today': 'اليوم',
    'notifications.group.yesterday': 'الأمس',
    'notifications.group.thisWeek': 'هذا الأسبوع',
    'notifications.group.older': 'سابق',
    'notifications.dismiss': 'تجاهل',
    'notifications.dismissConfirm': 'هل أنت متأكد من رغبتك في تجاهل هذا الإشعار؟',
    'notifications.noUnread': 'لا توجد إشعارات غير مقروءة',
    'notifications.allReadMessage': 'جميع الإشعارات مقروءة بالفعل.',
    'notifications.markAllReadConfirm': 'تحديد {count} إشعار كمقروء؟',

    // Notification Event Titles
    'notifications.event.subscription:created': 'الاشتراك نشط',
    'notifications.event.subscription:upgraded': 'تم ترقية الخطة',
    'notifications.event.subscription:downgraded': 'تم تغيير الخطة',
    'notifications.event.subscription:renewed': 'تم تجديد الاشتراك',
    'notifications.event.subscription:cancelled': 'تم إلغاء الاشتراك',
    'notifications.event.subscription:expired': 'انتهى الاشتراك',
    'notifications.event.subscription:expiring-soon': 'الاشتراك ينتهي قريبًا',
    'notifications.event.subscription:payment-failed': 'فشل الدفع',
    'notifications.event.subscription:trial-started': 'بدأت الفترة التجريبية',
    'notifications.event.subscription:trial-ending-soon': 'الفترة التجريبية تنتهي قريبًا',
    'notifications.event.subscription:trial-ended': 'انتهت الفترة التجريبية',
    'notifications.event.insight:published': 'محتوى جديد متاح',
    'notifications.event.insight:premium-published': 'محتوى مميز متاح',
    'notifications.event.insight:featured': 'محتوى مختار',
    'notifications.event.insight:trending': 'رائج الآن',
    'notifications.event.insight:saved': 'تم حفظ المحتوى',
    'notifications.event.engagement:insight-liked': 'شخص ما أعجب بمحتواك',
    'notifications.event.engagement:insight-commented': 'تعليق جديد',
    'notifications.event.engagement:user-followed': 'متابع جديد',
    'notifications.event.engagement:user-mentioned': 'تم ذكرك',
    'notifications.event.engagement:comment-replied': 'رد على تعليقك',
    'notifications.event.premium:content-available': 'محتوى حصري',
    'notifications.event.premium:early-access': 'وصول مبكر',
    'notifications.event.premium:special-offer': 'عرض خاص',
    'notifications.event.premium:webinar': 'دعوة لندوة عبر الإنترنت',
    'notifications.event.system:welcome': 'مرحباً بك في سيف كابيتال',
    'notifications.event.system:security-alert': 'تنبيه أمني',
    'notifications.event.system:account-activity': 'نشاط الحساب',
    'notifications.event.system:policy-update': 'تحديث السياسة',
    'notifications.event.system:maintenance': 'صيانة مجدولة',
    'notifications.event.system:app-update': 'تحديث متاح',
    'notifications.event.marketing:promotion': 'ترقية خاصة',
    'notifications.event.marketing:newsletter': 'النشرة الإخبارية',
    'notifications.event.marketing:survey': 'نحتاج لرأيك',
    'notifications.event.marketing:announcement': 'إعلان',

    // Notification Time
    'notifications.time.justNow': 'الآن',
    'notifications.time.minsAgo': 'منذ {count} دقيقة',
    'notifications.time.hoursAgo': 'منذ {count} ساعة',
    'notifications.time.daysAgo': 'منذ {count} يوم',

    // Legal
    'legal.terms.title': 'الشروط والأحكام',
    'legal.terms.header': 'الشروط والأحكام الخاصة باستخدام التطبيق',
    'legal.terms.sec1Title': '1. طبيعة الخدمة',
    'legal.terms.sec1Content': 'يقدّم التطبيق محتوى معلوماتي وتحليلي وتوصيات عامة متعلقة بالأسواق المالية لأغراض تثقيفية فقط، ولا يُعد استشارة استثمارية أو توصية رسمية أو ضمانًا لتحقيق أرباح.',
    'legal.terms.sec2Title': '2. إخلاء المسؤولية',
    'legal.terms.sec2Content1': 'يتحمّل المستخدم وحده المسؤولية الكاملة عن جميع قراراته الاستثمارية.',
    'legal.terms.sec2Content2': 'لا يتحمّل التطبيق أو مطوّروه أو القائمون عليه أي مسؤولية عن أي خسائر مالية مباشرة أو غير مباشرة ناتجة عن استخدام المحتوى.',
    'legal.terms.sec2Content3': 'يدرك المستخدم أن الاستثمار في الأسواق المالية ينطوي على مخاطر وقد يؤدي إلى خسارة رأس المال كليًا أو جزئيًا.',
    'legal.terms.sec3Title': '3. عدم مسؤولية المتاجر',
    'legal.terms.sec3Content1': 'يقرّ المستخدم ويوافق على أن Google Play Store و Apple App Store ليسا طرفًا في هذه الشروط ولا يتحمّلان أي مسؤولية عن محتوى التطبيق أو الخدمات المقدّمة من خلاله.',
    'legal.terms.sec3Content2': 'أي مطالبات أو نزاعات أو مسؤوليات تنشأ عن استخدام التطبيق تكون بين المستخدم وإدارة التطبيق فقط.',
    'legal.terms.sec4Title': '4. التزامات المستخدم',
    'legal.terms.sec4Content1': 'يلتزم المستخدم باستخدام التطبيق استخدامًا شخصيًا وقانونيًا فقط.',
    'legal.terms.sec4Content2': 'يلتزم بعدم إساءة استخدام التطبيق أو إعادة نشر محتواه بأي وسيلة كانت دون إذن مسبق.',
    'legal.terms.sec4Content3': 'يقرّ المستخدم بعدم الاعتماد الكلي على محتوى التطبيق دون استشارة مختص مالي مرخّص عند الحاجة.',
    'legal.terms.sec5Title': '5. الاشتراكات والمدفوعات',
    'legal.terms.sec5Content1': 'الاشتراكات المدفوعة تُدار من خلال Google Play أو Apple App Store وفقًا لسياسات كل متجر.',
    'legal.terms.sec5Content2': 'الرسوم المدفوعة غير قابلة للاسترداد بعد تفعيل الاشتراك، إلا وفق سياسات الاسترداد الخاصة بالمتجر المستخدم.',
    'legal.terms.sec5Content3': 'يتحمّل المستخدم مسؤولية إدارة الاشتراك أو إلغائه من خلال حسابه في المتجر.',
    'legal.terms.sec6Title': '6. حقوق الملكية الفكرية',
    'legal.terms.sec6Content': 'جميع الحقوق الفكرية المتعلقة بالتطبيق ومحتواه، بما في ذلك النصوص والتحليلات والتصاميم والبرمجيات، مملوكة حصريًا لإدارة التطبيق، ويُحظر نسخها أو استخدامها دون موافقة خطية مسبقة.',
    'legal.terms.sec7Title': '7. إيقاف أو تعليق الحساب',
    'legal.terms.sec7Content': 'يحق لإدارة التطبيق تعليق أو إيقاف حساب المستخدم في حال مخالفة هذه الشروط أو إساءة الاستخدام، دون أي التزام بتعويض.',
    'legal.terms.sec8Title': '8. تعديل الشروط',
    'legal.terms.sec8Content': 'يحتفظ التطبيق بحقه في تعديل أو تحديث هذه الشروط في أي وقت، ويُعد استمرار المستخدم في استخدام التطبيق بعد نشر التعديلات موافقة صريحة عليها.',
    'legal.terms.sec9Title': '9. القانون المنظّم والاختصاص القضائي',
    'legal.terms.sec9Content': 'تخضع هذه الشروط وتُفسَّر وفقًا لقوانين دولة الإمارات العربية المتحدة، وتختص محاكم الدولة بالفصل في أي نزاع ينشأ عنها.',
    'legal.terms.sec10Title': '10. الموافقة',
    'legal.terms.sec10Content': 'باستخدامك للتطبيق أو إنشاء حساب، فإنك تقرّ بأنك قرأت هذه الشروط وفهمتها ووافقت عليها بالكامل.',
  },
};

export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from storage on mount
  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage === 'en' || savedLanguage === 'ar') {
        setLanguageState(savedLanguage);
        // Set RTL if Arabic
        if (savedLanguage === 'ar') {
          I18nManager.forceRTL(true);
        }
      }
    } catch (error) {
      console.error('Failed to load language:', error);
    }
  };

  const saveLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    } catch (error) {
      console.error('Failed to save language:', error);
    }
  };

  const isRTL = useMemo(() => language === 'ar', [language]);

  const toggleLanguage = useCallback(() => {
    const newLang = language === 'en' ? 'ar' : 'en';
    setLanguageState(newLang);
    saveLanguage(newLang);

    // Toggle RTL
    const shouldBeRTL = newLang === 'ar';
    if (I18nManager.isRTL !== shouldBeRTL) {
      I18nManager.forceRTL(shouldBeRTL);
      // Note: On native, changing RTL requires app restart
      // We'll handle this gracefully in the UI
    }
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    saveLanguage(lang);

    // Set RTL
    const shouldBeRTL = lang === 'ar';
    if (I18nManager.isRTL !== shouldBeRTL) {
      I18nManager.forceRTL(shouldBeRTL);
    }
  }, []);

  const t = useCallback(
    (key: string, params?: Record<string, string | number>): string => {
      let translation = translations[language][key as keyof typeof translations.en] || key;

      if (params) {
        Object.entries(params).forEach(([paramKey, value]) => {
          translation = translation.replace(`{${paramKey}}`, String(value));
        });
      }

      return translation;
    },
    [language]
  );

  const value = useMemo(
    () => ({
      language,
      isRTL,
      toggleLanguage,
      setLanguage,
      t,
    }),
    [language, isRTL, toggleLanguage, setLanguage, t]
  );

  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
};

export const useLocalization = (): LocalizationContextType => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};
