export interface Country {
    code: string;
    name: {
        en: string;
        ar: string;
    };
    phoneCode: string;
}

export const COUNTRIES: Country[] = [
    { code: 'AF', name: { en: 'Afghanistan', ar: 'أفغانستان' }, phoneCode: '93' },
    { code: 'AL', name: { en: 'Albania', ar: 'ألبانيا' }, phoneCode: '355' },
    { code: 'DZ', name: { en: 'Algeria', ar: 'الجزائر' }, phoneCode: '213' },
    { code: 'AS', name: { en: 'American Samoa', ar: 'ساموا الأمريكية' }, phoneCode: '1-684' },
    { code: 'AD', name: { en: 'Andorra', ar: 'أندورا' }, phoneCode: '376' },
    { code: 'AO', name: { en: 'Angola', ar: 'أنغولا' }, phoneCode: '244' },
    { code: 'AI', name: { en: 'Anguilla', ar: 'أنغويلا' }, phoneCode: '1-264' },
    { code: 'AQ', name: { en: 'Antarctica', ar: 'أنتاركتيكا' }, phoneCode: '672' },
    { code: 'AG', name: { en: 'Antigua and Barbuda', ar: 'أنتيغوا وبربودا' }, phoneCode: '1-268' },
    { code: 'AR', name: { en: 'Argentina', ar: 'الأرجنتين' }, phoneCode: '54' },
    { code: 'AM', name: { en: 'Armenia', ar: 'أرمينيا' }, phoneCode: '374' },
    { code: 'AW', name: { en: 'Aruba', ar: 'أروبا' }, phoneCode: '297' },
    { code: 'AU', name: { en: 'Australia', ar: 'أستراليا' }, phoneCode: '61' },
    { code: 'AT', name: { en: 'Austria', ar: 'النمسا' }, phoneCode: '43' },
    { code: 'AZ', name: { en: 'Azerbaijan', ar: 'أذربيجان' }, phoneCode: '994' },
    { code: 'BS', name: { en: 'Bahamas', ar: 'جزر البهاما' }, phoneCode: '1-242' },
    { code: 'BH', name: { en: 'Bahrain', ar: 'البحرين' }, phoneCode: '973' },
    { code: 'BD', name: { en: 'Bangladesh', ar: 'بنغلاديش' }, phoneCode: '880' },
    { code: 'BB', name: { en: 'Barbados', ar: 'باربادوس' }, phoneCode: '1-246' },
    { code: 'BY', name: { en: 'Belarus', ar: 'بيلاروسيا' }, phoneCode: '375' },
    { code: 'BE', name: { en: 'Belgium', ar: 'بلجيكا' }, phoneCode: '32' },
    { code: 'BZ', name: { en: 'Belize', ar: 'بليز' }, phoneCode: '501' },
    { code: 'BJ', name: { en: 'Benin', ar: 'بنين' }, phoneCode: '229' },
    { code: 'BM', name: { en: 'Bermuda', ar: 'برمودا' }, phoneCode: '1-441' },
    { code: 'BT', name: { en: 'Bhutan', ar: 'بوتان' }, phoneCode: '975' },
    { code: 'BO', name: { en: 'Bolivia', ar: 'بوليفيا' }, phoneCode: '591' },
    { code: 'BA', name: { en: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك' }, phoneCode: '387' },
    { code: 'BW', name: { en: 'Botswana', ar: 'بوتسوانا' }, phoneCode: '267' },
    { code: 'BR', name: { en: 'Brazil', ar: 'البرازيل' }, phoneCode: '55' },
    { code: 'IO', name: { en: 'British Indian Ocean Territory', ar: 'إقليم المحيط الهندي البريطاني' }, phoneCode: '246' },
    { code: 'VG', name: { en: 'British Virgin Islands', ar: 'جزر العذراء البريطانية' }, phoneCode: '1-284' },
    { code: 'BN', name: { en: 'Brunei', ar: 'بروناي' }, phoneCode: '673' },
    { code: 'BG', name: { en: 'Bulgaria', ar: 'بلغاريا' }, phoneCode: '359' },
    { code: 'BF', name: { en: 'Burkina Faso', ar: 'بوركينا فاسو' }, phoneCode: '226' },
    { code: 'BI', name: { en: 'Burundi', ar: 'بوروندي' }, phoneCode: '257' },
    { code: 'KH', name: { en: 'Cambodia', ar: 'كمبوديا' }, phoneCode: '855' },
    { code: 'CM', name: { en: 'Cameroon', ar: 'الكاميرون' }, phoneCode: '237' },
    { code: 'CA', name: { en: 'Canada', ar: 'كندا' }, phoneCode: '1' },
    { code: 'CV', name: { en: 'Cape Verde', ar: 'الرأس الأخضر' }, phoneCode: '238' },
    { code: 'KY', name: { en: 'Cayman Islands', ar: 'جزر كايمان' }, phoneCode: '1-345' },
    { code: 'CF', name: { en: 'Central African Republic', ar: 'جمهورية أفريقيا الوسطى' }, phoneCode: '236' },
    { code: 'TD', name: { en: 'Chad', ar: 'تشاد' }, phoneCode: '235' },
    { code: 'CL', name: { en: 'Chile', ar: 'تشيلي' }, phoneCode: '56' },
    { code: 'CN', name: { en: 'China', ar: 'الصين' }, phoneCode: '86' },
    { code: 'CX', name: { en: 'Christmas Island', ar: 'جزيرة عيد الميلاد' }, phoneCode: '61' },
    { code: 'CC', name: { en: 'Cocos Islands', ar: 'جزر كوكوس' }, phoneCode: '61' },
    { code: 'CO', name: { en: 'Colombia', ar: 'كولومبيا' }, phoneCode: '57' },
    { code: 'KM', name: { en: 'Comoros', ar: 'جزر القمر' }, phoneCode: '269' },
    { code: 'CK', name: { en: 'Cook Islands', ar: 'جزر كوك' }, phoneCode: '682' },
    { code: 'CR', name: { en: 'Costa Rica', ar: 'كوستاريكا' }, phoneCode: '506' },
    { code: 'HR', name: { en: 'Croatia', ar: 'كرواتيا' }, phoneCode: '385' },
    { code: 'CU', name: { en: 'Cuba', ar: 'كوبا' }, phoneCode: '53' },
    { code: 'CW', name: { en: 'Curacao', ar: 'كوراساو' }, phoneCode: '599' },
    { code: 'CY', name: { en: 'Cyprus', ar: 'قبرص' }, phoneCode: '357' },
    { code: 'CZ', name: { en: 'Czech Republic', ar: 'الجمهورية التشيكية' }, phoneCode: '420' },
    { code: 'CD', name: { en: 'Democratic Republic of the Congo', ar: 'جمهورية الكونغو الديمقراطية' }, phoneCode: '243' },
    { code: 'DK', name: { en: 'Denmark', ar: 'الدانمرك' }, phoneCode: '45' },
    { code: 'DJ', name: { en: 'Djibouti', ar: 'جيبوتي' }, phoneCode: '253' },
    { code: 'DM', name: { en: 'Dominica', ar: 'دومينيكا' }, phoneCode: '1-767' },
    { code: 'DO', name: { en: 'Dominican Republic', ar: 'جمهورية الدومينيكان' }, phoneCode: '1-809' },
    { code: 'TL', name: { en: 'East Timor', ar: 'تيمور الشرقية' }, phoneCode: '670' },
    { code: 'EC', name: { en: 'Ecuador', ar: 'إكوادور' }, phoneCode: '593' },
    { code: 'EG', name: { en: 'Egypt', ar: 'مصر' }, phoneCode: '20' },
    { code: 'SV', name: { en: 'El Salvador', ar: 'السلفادور' }, phoneCode: '503' },
    { code: 'GQ', name: { en: 'Equatorial Guinea', ar: 'غينيا الاستوائية' }, phoneCode: '240' },
    { code: 'ER', name: { en: 'Eritrea', ar: 'إريتريا' }, phoneCode: '291' },
    { code: 'EE', name: { en: 'Estonia', ar: 'إستونيا' }, phoneCode: '372' },
    { code: 'ET', name: { en: 'Ethiopia', ar: 'إثيوبيا' }, phoneCode: '251' },
    { code: 'FK', name: { en: 'Falkland Islands', ar: 'جزر فوكلاند' }, phoneCode: '500' },
    { code: 'FO', name: { en: 'Faroe Islands', ar: 'جزر فارو' }, phoneCode: '298' },
    { code: 'FJ', name: { en: 'Fiji', ar: 'فيجي' }, phoneCode: '679' },
    { code: 'FI', name: { en: 'Finland', ar: 'فنلندا' }, phoneCode: '358' },
    { code: 'FR', name: { en: 'France', ar: 'فرنسا' }, phoneCode: '33' },
    { code: 'PF', name: { en: 'French Polynesia', ar: 'بولينيزيا الفرنسية' }, phoneCode: '689' },
    { code: 'GA', name: { en: 'Gabon', ar: 'الغابون' }, phoneCode: '241' },
    { code: 'GM', name: { en: 'Gambia', ar: 'غامبيا' }, phoneCode: '220' },
    { code: 'GE', name: { en: 'Georgia', ar: 'جورجيا' }, phoneCode: '995' },
    { code: 'DE', name: { en: 'Germany', ar: 'ألمانيا' }, phoneCode: '49' },
    { code: 'GH', name: { en: 'Ghana', ar: 'غانا' }, phoneCode: '233' },
    { code: 'GI', name: { en: 'Gibraltar', ar: 'جبل طارق' }, phoneCode: '350' },
    { code: 'GR', name: { en: 'Greece', ar: 'اليونان' }, phoneCode: '30' },
    { code: 'GL', name: { en: 'Greenland', ar: 'غرينلاند' }, phoneCode: '299' },
    { code: 'GD', name: { en: 'Grenada', ar: 'غرينادا' }, phoneCode: '1-473' },
    { code: 'GU', name: { en: 'Guam', ar: 'غوام' }, phoneCode: '1-671' },
    { code: 'GT', name: { en: 'Guatemala', ar: 'غواتيمالا' }, phoneCode: '502' },
    { code: 'GG', name: { en: 'Guernsey', ar: 'غيرنزي' }, phoneCode: '44-1481' },
    { code: 'GN', name: { en: 'Guinea', ar: 'غينيا' }, phoneCode: '224' },
    { code: 'GW', name: { en: 'Guinea-Bissau', ar: 'غينيا بيساو' }, phoneCode: '245' },
    { code: 'GY', name: { en: 'Guyana', ar: 'غويانا' }, phoneCode: '592' },
    { code: 'HT', name: { en: 'Haiti', ar: 'هاييتي' }, phoneCode: '509' },
    { code: 'HN', name: { en: 'Honduras', ar: 'هندوراس' }, phoneCode: '504' },
    { code: 'HK', name: { en: 'Hong Kong', ar: 'هونغ كونغ' }, phoneCode: '852' },
    { code: 'HU', name: { en: 'Hungary', ar: 'المجر' }, phoneCode: '36' },
    { code: 'IS', name: { en: 'Iceland', ar: 'آيسلندا' }, phoneCode: '354' },
    { code: 'IN', name: { en: 'India', ar: 'الهند' }, phoneCode: '91' },
    { code: 'ID', name: { en: 'Indonesia', ar: 'إندونيسيا' }, phoneCode: '62' },
    { code: 'IR', name: { en: 'Iran', ar: 'إيران' }, phoneCode: '98' },
    { code: 'IQ', name: { en: 'Iraq', ar: 'العراق' }, phoneCode: '964' },
    { code: 'IE', name: { en: 'Ireland', ar: 'أيرلندا' }, phoneCode: '353' },
    { code: 'IM', name: { en: 'Isle of Man', ar: 'جزيرة مان' }, phoneCode: '44-1624' },
    { code: 'IL', name: { en: 'Israel', ar: 'إسرائيل' }, phoneCode: '972' },
    { code: 'IT', name: { en: 'Italy', ar: 'إيطاليا' }, phoneCode: '39' },
    { code: 'CI', name: { en: 'Ivory Coast', ar: 'ساحل العاج' }, phoneCode: '225' },
    { code: 'JM', name: { en: 'Jamaica', ar: 'جامايكا' }, phoneCode: '1-876' },
    { code: 'JP', name: { en: 'Japan', ar: 'اليابان' }, phoneCode: '81' },
    { code: 'JE', name: { en: 'Jersey', ar: 'جيرزي' }, phoneCode: '44-1534' },
    { code: 'JO', name: { en: 'Jordan', ar: 'الأردن' }, phoneCode: '962' },
    { code: 'KZ', name: { en: 'Kazakhstan', ar: 'كازاخستان' }, phoneCode: '7' },
    { code: 'KE', name: { en: 'Kenya', ar: 'كينيا' }, phoneCode: '254' },
    { code: 'KI', name: { en: 'Kiribati', ar: 'كيريباتي' }, phoneCode: '686' },
    { code: 'XK', name: { en: 'Kosovo', ar: 'كوسوفو' }, phoneCode: '383' },
    { code: 'KW', name: { en: 'Kuwait', ar: 'الكويت' }, phoneCode: '965' },
    { code: 'KG', name: { en: 'Kyrgyzstan', ar: 'قيرغيزستان' }, phoneCode: '996' },
    { code: 'LA', name: { en: 'Laos', ar: 'لاوس' }, phoneCode: '856' },
    { code: 'LV', name: { en: 'Latvia', ar: 'لاتفيا' }, phoneCode: '371' },
    { code: 'LB', name: { en: 'Lebanon', ar: 'لبنان' }, phoneCode: '961' },
    { code: 'LS', name: { en: 'Lesotho', ar: 'ليسوتو' }, phoneCode: '266' },
    { code: 'LR', name: { en: 'Liberia', ar: 'ليبيريا' }, phoneCode: '231' },
    { code: 'LY', name: { en: 'Libya', ar: 'ليبيا' }, phoneCode: '218' },
    { code: 'LI', name: { en: 'Liechtenstein', ar: 'ليختنشتاين' }, phoneCode: '423' },
    { code: 'LT', name: { en: 'Lithuania', ar: 'ليتوانيا' }, phoneCode: '370' },
    { code: 'LU', name: { en: 'Luxembourg', ar: 'لوكسمبورغ' }, phoneCode: '352' },
    { code: 'MO', name: { en: 'Macao', ar: 'ماكاو' }, phoneCode: '853' },
    { code: 'MK', name: { en: 'Macedonia', ar: 'مقدونيا' }, phoneCode: '389' },
    { code: 'MG', name: { en: 'Madagascar', ar: 'مدغشقر' }, phoneCode: '261' },
    { code: 'MW', name: { en: 'Malawi', ar: 'مالاوي' }, phoneCode: '265' },
    { code: 'MY', name: { en: 'Malaysia', ar: 'ماليزيا' }, phoneCode: '60' },
    { code: 'MV', name: { en: 'Maldives', ar: 'جزر المالديف' }, phoneCode: '960' },
    { code: 'ML', name: { en: 'Mali', ar: 'مالي' }, phoneCode: '223' },
    { code: 'MT', name: { en: 'Malta', ar: 'مالطا' }, phoneCode: '356' },
    { code: 'MH', name: { en: 'Marshall Islands', ar: 'جزر مارشال' }, phoneCode: '692' },
    { code: 'MR', name: { en: 'Mauritania', ar: 'موريتانيا' }, phoneCode: '222' },
    { code: 'MU', name: { en: 'Mauritius', ar: 'موريشيوس' }, phoneCode: '230' },
    { code: 'YT', name: { en: 'Mayotte', ar: 'مايوت' }, phoneCode: '262' },
    { code: 'MX', name: { en: 'Mexico', ar: 'المكسيك' }, phoneCode: '52' },
    { code: 'FM', name: { en: 'Micronesia', ar: 'ميكرونيزيا' }, phoneCode: '691' },
    { code: 'MD', name: { en: 'Moldova', ar: 'مولدوفا' }, phoneCode: '373' },
    { code: 'MC', name: { en: 'Monaco', ar: 'موناكو' }, phoneCode: '377' },
    { code: 'MN', name: { en: 'Mongolia', ar: 'منغوليا' }, phoneCode: '976' },
    { code: 'ME', name: { en: 'Montenegro', ar: 'الجبل الأسود' }, phoneCode: '382' },
    { code: 'MS', name: { en: 'Montserrat', ar: 'مونتسيرات' }, phoneCode: '1-664' },
    { code: 'MA', name: { en: 'Morocco', ar: 'المغرب' }, phoneCode: '212' },
    { code: 'MZ', name: { en: 'Mozambique', ar: 'موزمبيق' }, phoneCode: '258' },
    { code: 'MM', name: { en: 'Myanmar', ar: 'ميانمار' }, phoneCode: '95' },
    { code: 'NA', name: { en: 'Namibia', ar: 'ناميبيا' }, phoneCode: '264' },
    { code: 'NR', name: { en: 'Nauru', ar: 'ناورو' }, phoneCode: '674' },
    { code: 'NP', name: { en: 'Nepal', ar: 'نيبال' }, phoneCode: '977' },
    { code: 'NL', name: { en: 'Netherlands', ar: 'هولندا' }, phoneCode: '31' },
    { code: 'NC', name: { en: 'New Caledonia', ar: 'كاليدونيا الجديدة' }, phoneCode: '687' },
    { code: 'NZ', name: { en: 'New Zealand', ar: 'نيوزيلندا' }, phoneCode: '64' },
    { code: 'NI', name: { en: 'Nicaragua', ar: 'نيكاراغوا' }, phoneCode: '505' },
    { code: 'NE', name: { en: 'Niger', ar: 'النيجر' }, phoneCode: '227' },
    { code: 'NG', name: { en: 'Nigeria', ar: 'نيجيريا' }, phoneCode: '234' },
    { code: 'NU', name: { en: 'Niue', ar: 'نيوي' }, phoneCode: '683' },
    { code: 'KP', name: { en: 'North Korea', ar: 'كوريا الشمالية' }, phoneCode: '850' },
    { code: 'MP', name: { en: 'Northern Mariana Islands', ar: 'جزر ماريانا الشمالية' }, phoneCode: '1-670' },
    { code: 'NO', name: { en: 'Norway', ar: 'النرويج' }, phoneCode: '47' },
    { code: 'OM', name: { en: 'Oman', ar: 'عمان' }, phoneCode: '968' },
    { code: 'PK', name: { en: 'Pakistan', ar: 'باكستان' }, phoneCode: '92' },
    { code: 'PW', name: { en: 'Palau', ar: 'بالاو' }, phoneCode: '680' },
    { code: 'PS', name: { en: 'Palestine', ar: 'فلسطين' }, phoneCode: '970' },
    { code: 'PA', name: { en: 'Panama', ar: 'بنما' }, phoneCode: '507' },
    { code: 'PG', name: { en: 'Papua New Guinea', ar: 'بابوا غينيا الجديدة' }, phoneCode: '675' },
    { code: 'PY', name: { en: 'Paraguay', ar: 'باراغواي' }, phoneCode: '595' },
    { code: 'PE', name: { en: 'Peru', ar: 'بيرو' }, phoneCode: '51' },
    { code: 'PH', name: { en: 'Philippines', ar: 'الفلبين' }, phoneCode: '63' },
    { code: 'PN', name: { en: 'Pitcairn', ar: 'بيتكيرن' }, phoneCode: '64' },
    { code: 'PL', name: { en: 'Poland', ar: 'بولندا' }, phoneCode: '48' },
    { code: 'PT', name: { en: 'Portugal', ar: 'البرتغال' }, phoneCode: '351' },
    { code: 'PR', name: { en: 'Puerto Rico', ar: 'بورتوريكو' }, phoneCode: '1-787' },
    { code: 'QA', name: { en: 'Qatar', ar: 'قطر' }, phoneCode: '974' },
    { code: 'CG', name: { en: 'Republic of the Congo', ar: 'جمهورية الكونغو' }, phoneCode: '242' },
    { code: 'RE', name: { en: 'Reunion', ar: 'ريونيون' }, phoneCode: '262' },
    { code: 'RO', name: { en: 'Romania', ar: 'رومانيا' }, phoneCode: '40' },
    { code: 'RU', name: { en: 'Russia', ar: 'روسيا' }, phoneCode: '7' },
    { code: 'RW', name: { en: 'Rwanda', ar: 'رواندا' }, phoneCode: '250' },
    { code: 'BL', name: { en: 'Saint Barthelemy', ar: 'سان بارتليمي' }, phoneCode: '590' },
    { code: 'SH', name: { en: 'Saint Helena', ar: 'سانت هيلينا' }, phoneCode: '290' },
    { code: 'KN', name: { en: 'Saint Kitts and Nevis', ar: 'سانت كيتس ونيفيس' }, phoneCode: '1-869' },
    { code: 'LC', name: { en: 'Saint Lucia', ar: 'سانت لوسيا' }, phoneCode: '1-758' },
    { code: 'MF', name: { en: 'Saint Martin', ar: 'سانت مارتن' }, phoneCode: '590' },
    { code: 'PM', name: { en: 'Saint Pierre and Miquelon', ar: 'سان بيير وميكلون' }, phoneCode: '508' },
    { code: 'VC', name: { en: 'Saint Vincent and the Grenadines', ar: 'سانت فينسنت والغرينادين' }, phoneCode: '1-784' },
    { code: 'WS', name: { en: 'Samoa', ar: 'ساموا' }, phoneCode: '685' },
    { code: 'SM', name: { en: 'San Marino', ar: 'سان مارينو' }, phoneCode: '378' },
    { code: 'ST', name: { en: 'Sao Tome and Principe', ar: 'ساو تومي وبرينسيبي' }, phoneCode: '239' },
    { code: 'SA', name: { en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' }, phoneCode: '966' },
    { code: 'SN', name: { en: 'Senegal', ar: 'السنغال' }, phoneCode: '221' },
    { code: 'RS', name: { en: 'Serbia', ar: 'صربيا' }, phoneCode: '381' },
    { code: 'SC', name: { en: 'Seychelles', ar: 'سيشل' }, phoneCode: '248' },
    { code: 'SL', name: { en: 'Sierra Leone', ar: 'سيراليون' }, phoneCode: '232' },
    { code: 'SG', name: { en: 'Singapore', ar: 'سنغافورة' }, phoneCode: '65' },
    { code: 'SX', name: { en: 'Sint Maarten', ar: 'سانت مارتن' }, phoneCode: '1-721' },
    { code: 'SK', name: { en: 'Slovakia', ar: 'سلوفاكيا' }, phoneCode: '421' },
    { code: 'SI', name: { en: 'Slovenia', ar: 'سلوفينيا' }, phoneCode: '386' },
    { code: 'SB', name: { en: 'Solomon Islands', ar: 'جزر سليمان' }, phoneCode: '677' },
    { code: 'SO', name: { en: 'Somalia', ar: 'الصومال' }, phoneCode: '252' },
    { code: 'ZA', name: { en: 'South Africa', ar: 'جنوب أفريقيا' }, phoneCode: '27' },
    { code: 'KR', name: { en: 'South Korea', ar: 'كوريا الجنوبية' }, phoneCode: '82' },
    { code: 'SS', name: { en: 'South Sudan', ar: 'جنوب السودان' }, phoneCode: '211' },
    { code: 'ES', name: { en: 'Spain', ar: 'إسبانيا' }, phoneCode: '34' },
    { code: 'LK', name: { en: 'Sri Lanka', ar: 'سريلانكا' }, phoneCode: '94' },
    { code: 'SD', name: { en: 'Sudan', ar: 'السودان' }, phoneCode: '249' },
    { code: 'SR', name: { en: 'Suriname', ar: 'سورينام' }, phoneCode: '597' },
    { code: 'SJ', name: { en: 'Svalbard and Jan Mayen', ar: 'سفالبارد ويان ماين' }, phoneCode: '47' },
    { code: 'SZ', name: { en: 'Swaziland', ar: 'سوازيلاند' }, phoneCode: '268' },
    { code: 'SE', name: { en: 'Sweden', ar: 'السويد' }, phoneCode: '46' },
    { code: 'CH', name: { en: 'Switzerland', ar: 'سويسرا' }, phoneCode: '41' },
    { code: 'SY', name: { en: 'Syria', ar: 'سوريا' }, phoneCode: '963' },
    { code: 'TW', name: { en: 'Taiwan', ar: 'تايوان' }, phoneCode: '886' },
    { code: 'TJ', name: { en: 'Tajikistan', ar: 'طاجيكستان' }, phoneCode: '992' },
    { code: 'TZ', name: { en: 'Tanzania', ar: 'تنزانيا' }, phoneCode: '255' },
    { code: 'TH', name: { en: 'Thailand', ar: 'تايلاند' }, phoneCode: '66' },
    { code: 'TG', name: { en: 'Togo', ar: 'توغو' }, phoneCode: '228' },
    { code: 'TK', name: { en: 'Tokelau', ar: 'توكيلاو' }, phoneCode: '690' },
    { code: 'TO', name: { en: 'Tonga', ar: 'تونغا' }, phoneCode: '676' },
    { code: 'TT', name: { en: 'Trinidad and Barbuda', ar: 'ترينيداد وتوباغو' }, phoneCode: '1-868' },
    { code: 'TN', name: { en: 'Tunisia', ar: 'تونس' }, phoneCode: '216' },
    { code: 'TR', name: { en: 'Turkey', ar: 'تركيا' }, phoneCode: '90' },
    { code: 'TM', name: { en: 'Turkmenistan', ar: 'تركمانستان' }, phoneCode: '993' },
    { code: 'TC', name: { en: 'Turks and Caicos Islands', ar: 'جزر تركس وكايكوس' }, phoneCode: '1-649' },
    { code: 'TV', name: { en: 'Tuvalu', ar: 'توفالو' }, phoneCode: '688' },
    { code: 'VI', name: { en: 'U.S. Virgin Islands', ar: 'جزر العذراء الأمريكية' }, phoneCode: '1-340' },
    { code: 'UG', name: { en: 'Uganda', ar: 'أوغندا' }, phoneCode: '256' },
    { code: 'UA', name: { en: 'Ukraine', ar: 'أوكرانيا' }, phoneCode: '380' },
    { code: 'UAE', name: { en: 'United Arab Emirates', ar: 'الإمارات العربية المتحدة' }, phoneCode: '971' },
    { code: 'UK', name: { en: 'United Kingdom', ar: 'المملكة المتحدة' }, phoneCode: '44' },
    { code: 'US', name: { en: 'United States', ar: 'الولايات المتحدة' }, phoneCode: '1' },
    { code: 'UY', name: { en: 'Uruguay', ar: 'أوروغواي' }, phoneCode: '598' },
    { code: 'UZ', name: { en: 'Uzbekistan', ar: 'أوزبكستان' }, phoneCode: '998' },
    { code: 'VU', name: { en: 'Vanuatu', ar: 'فانواتو' }, phoneCode: '678' },
    { code: 'VA', name: { en: 'Vatican', ar: 'الفاتيكان' }, phoneCode: '379' },
    { code: 'VE', name: { en: 'Venezuela', ar: 'فنزويلا' }, phoneCode: '58' },
    { code: 'VN', name: { en: 'Vietnam', ar: 'فيتنام' }, phoneCode: '84' },
    { code: 'WF', name: { en: 'Wallis and Futuna', ar: 'واليس وفوتونا' }, phoneCode: '681' },
    { code: 'EH', name: { en: 'Western Sahara', ar: 'الصحراء الغربية' }, phoneCode: '212' },
    { code: 'YE', name: { en: 'Yemen', ar: 'اليمن' }, phoneCode: '967' },
    { code: 'ZM', name: { en: 'Zambia', ar: 'زامبيا' }, phoneCode: '260' },
    { code: 'ZW', name: { en: 'Zimbabwe', ar: 'زيمبابوي' }, phoneCode: '263' },
];
